//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////

#ifndef __UNIX_CONCRETECOMPONENT_H
#define __UNIX_CONCRETECOMPONENT_H


#include "CIM_Component.h"
#include <OtherOrganizationInformation/UNIX_OtherOrganizationInformation.h>
#include <DirectorySpecification/UNIX_DirectorySpecification.h>
#include <MemoryCheck/UNIX_MemoryCheck.h>
#include <VersionCompatibilityCheck/UNIX_VersionCompatibilityCheck.h>
#include <DiskSpaceCheck/UNIX_DiskSpaceCheck.h>
#include <SoftwareElementVersionCheck/UNIX_SoftwareElementVersionCheck.h>
#include <FileSpecification/UNIX_FileSpecification.h>
#include <ArchitectureCheck/UNIX_ArchitectureCheck.h>
#include <OSVersionCheck/UNIX_OSVersionCheck.h>
#include <SettingCheck/UNIX_SettingCheck.h>
#include <SwapSpaceCheck/UNIX_SwapSpaceCheck.h>
#include <RegisteredSubProfile/UNIX_RegisteredSubProfile.h>
#include <RejectConnectionAction/UNIX_RejectConnectionAction.h>
#include <VendorPolicyAction/UNIX_VendorPolicyAction.h>
#include <NetworkPacketAction/UNIX_NetworkPacketAction.h>
#include <MethodAction/UNIX_MethodAction.h>
#include <CompoundPolicyAction/UNIX_CompoundPolicyAction.h>
#include <IKEAction/UNIX_IKEAction.h>
#include <IPsecTunnelAction/UNIX_IPsecTunnelAction.h>
#include <IPsecTransportAction/UNIX_IPsecTransportAction.h>
#include <PreconfiguredTunnelAction/UNIX_PreconfiguredTunnelAction.h>
#include <PreconfiguredTransportAction/UNIX_PreconfiguredTransportAction.h>
#include <IPsecRule/UNIX_IPsecRule.h>
#include <IKERule/UNIX_IKERule.h>
#include <AuthenticationRule/UNIX_AuthenticationRule.h>
#include <PolicyGroup/UNIX_PolicyGroup.h>
#include <VendorPolicyCondition/UNIX_VendorPolicyCondition.h>
#include <DocumentAuthentication/UNIX_DocumentAuthentication.h>
#include <PublicPrivateKeyAuthentication/UNIX_PublicPrivateKeyAuthentication.h>
#include <KerberosAuthentication/UNIX_KerberosAuthentication.h>
#include <NetworkingIDAuthentication/UNIX_NetworkingIDAuthentication.h>
#include <SharedSecretAuthentication/UNIX_SharedSecretAuthentication.h>
#include <PhysicalCredentialAuthentication/UNIX_PhysicalCredentialAuthentication.h>
#include <AccountAuthentication/UNIX_AccountAuthentication.h>
#include <BiometricAuthentication/UNIX_BiometricAuthentication.h>
#include <PolicyTimePeriodCondition/UNIX_PolicyTimePeriodCondition.h>
#include <QueryCondition/UNIX_QueryCondition.h>
#include <PacketFilterCondition/UNIX_PacketFilterCondition.h>
#include <CompoundPolicyCondition/UNIX_CompoundPolicyCondition.h>
#include <StorageError/UNIX_StorageError.h>
#include <MemoryError/UNIX_MemoryError.h>
#include <Configuration/UNIX_Configuration.h>
#include <RebootAction/UNIX_RebootAction.h>
#include <ExecuteProgram/UNIX_ExecuteProgram.h>
#include <CopyFileAction/UNIX_CopyFileAction.h>
#include <RemoveFileAction/UNIX_RemoveFileAction.h>
#include <ModifySettingAction/UNIX_ModifySettingAction.h>
#include <RemoveDirectoryAction/UNIX_RemoveDirectoryAction.h>
#include <CreateDirectoryAction/UNIX_CreateDirectoryAction.h>
#include <FRU/UNIX_FRU.h>
#include <BaseMetricValue/UNIX_BaseMetricValue.h>
#include <AggregationMetricValue/UNIX_AggregationMetricValue.h>
#include <View/UNIX_View.h>
#include <PhysicalComputerSystemView/UNIX_PhysicalComputerSystemView.h>
#include <SupportAccess/UNIX_SupportAccess.h>
#include <Product/UNIX_Product.h>
#include <SystemConfiguration/UNIX_SystemConfiguration.h>
#include <SystemSetting/UNIX_SystemSetting.h>
#include <VideoControllerResolution/UNIX_VideoControllerResolution.h>
#include <DiagnosticSetting/UNIX_DiagnosticSetting.h>
#include <TimeZone/UNIX_TimeZone.h>
#include <MonitorResolution/UNIX_MonitorResolution.h>
#include <OtherGroupInformation/UNIX_OtherGroupInformation.h>
#include <PhysicalLink/UNIX_PhysicalLink.h>
#include <PhysicalMedia/UNIX_PhysicalMedia.h>
#include <PhysicalTape/UNIX_PhysicalTape.h>
#include <Chip/UNIX_Chip.h>
#include <PhysicalMemory/UNIX_PhysicalMemory.h>
#include <PhysicalConnector/UNIX_PhysicalConnector.h>
#include <Slot/UNIX_Slot.h>
#include <Card/UNIX_Card.h>
#include <SystemBusCard/UNIX_SystemBusCard.h>
#include <Rack/UNIX_Rack.h>
#include <Chassis/UNIX_Chassis.h>
#include <PackageLocation/UNIX_PackageLocation.h>
#include <StorageMediaLocation/UNIX_StorageMediaLocation.h>
#include <Magazine/UNIX_Magazine.h>
#include <AuthenticationRequirement/UNIX_AuthenticationRequirement.h>
#include <BGPRouteMap/UNIX_BGPRouteMap.h>
#include <AccessControlInformation/UNIX_AccessControlInformation.h>
#include <StoragePool/UNIX_StoragePool.h>
#include <ConcreteJob/UNIX_ConcreteJob.h>
#include <PrintJob/UNIX_PrintJob.h>
#include <DataFile/UNIX_DataFile.h>
#include <FIFOPipeFile/UNIX_FIFOPipeFile.h>
#include <DeviceFile/UNIX_DeviceFile.h>
#include <DeviceFile/UNIX_DeviceFile.h>
#include <Directory/UNIX_Directory.h>
#include <UnixDirectory/UNIX_UnixDirectory.h>
#include <SymbolicLink/UNIX_SymbolicLink.h>
#include <BGPPathAttributes/UNIX_BGPPathAttributes.h>
#include <File/UNIX_File.h>
#include <FileSystem/UNIX_FileSystem.h>
#include <RemoteFileSystem/UNIX_RemoteFileSystem.h>
#include <NFS/UNIX_NFS.h>
#include <DatabaseStorageArea/UNIX_DatabaseStorageArea.h>
#include <LocalFileSystem/UNIX_LocalFileSystem.h>
#include <LocalFileSystem/UNIX_LocalFileSystem.h>
#include <ApplicationSystem/UNIX_ApplicationSystem.h>
#include <DatabaseSystem/UNIX_DatabaseSystem.h>
#include <VirtualComputerSystem/UNIX_VirtualComputerSystem.h>
#include <ComputerSystem/UNIX_ComputerSystem.h>
#include <Cluster/UNIX_Cluster.h>
#include <StorageLibrary/UNIX_StorageLibrary.h>
#include <ReusablePolicyContainer/UNIX_ReusablePolicyContainer.h>
#include <RoutingProtocolDomain/UNIX_RoutingProtocolDomain.h>
#include <OSPFArea/UNIX_OSPFArea.h>
#include <Network/UNIX_Network.h>
#include <PolicyRepository/UNIX_PolicyRepository.h>
#include <AutonomousSystem/UNIX_AutonomousSystem.h>
#include <DMA/UNIX_DMA.h>
#include <MemoryResource/UNIX_MemoryResource.h>
#include <PortResource/UNIX_PortResource.h>
#include <IRQ/UNIX_IRQ.h>
#include <Process/UNIX_Process.h>
#include <MessageLog/UNIX_MessageLog.h>
#include <DiagnosticLog/UNIX_DiagnosticLog.h>
#include <DiagnosticsLog/UNIX_DiagnosticsLog.h>
#include <OperatingSystem/UNIX_OperatingSystem.h>
#include <Account/UNIX_Account.h>
#include <JobQueue/UNIX_JobQueue.h>
#include <PrintQueue/UNIX_PrintQueue.h>
#include <Thread/UNIX_Thread.h>
#include <CommonDatabase/UNIX_CommonDatabase.h>
#include <LogicalModule/UNIX_LogicalModule.h>
#include <PassThroughModule/UNIX_PassThroughModule.h>
#include <LabelReader/UNIX_LabelReader.h>
#include <Scanner/UNIX_Scanner.h>
#include <ProtocolController/UNIX_ProtocolController.h>
#include <SCSIProtocolController/UNIX_SCSIProtocolController.h>
#include <WiFiRadio/UNIX_WiFiRadio.h>
#include <HeatPipe/UNIX_HeatPipe.h>
#include <Refrigeration/UNIX_Refrigeration.h>
#include <Fan/UNIX_Fan.h>
#include <PowerSource/UNIX_PowerSource.h>
#include <DesktopMonitor/UNIX_DesktopMonitor.h>
#include <FlatPanel/UNIX_FlatPanel.h>
#include <Keyboard/UNIX_Keyboard.h>
#include <PointingDevice/UNIX_PointingDevice.h>
#include <CableModem/UNIX_CableModem.h>
#include <SDSLModem/UNIX_SDSLModem.h>
#include <HDSLModem/UNIX_HDSLModem.h>
#include <VDSLModem/UNIX_VDSLModem.h>
#include <ADSLModem/UNIX_ADSLModem.h>
#include <POTSModem/UNIX_POTSModem.h>
#include <Unimodem/UNIX_Unimodem.h>
#include <ISDNModem/UNIX_ISDNModem.h>
#include <FibrePort/UNIX_FibrePort.h>
#include <FCPort/UNIX_FCPort.h>
#include <EthernetPort/UNIX_EthernetPort.h>
#include <LLDPEthernetPort/UNIX_LLDPEthernetPort.h>
#include <WiFiPort/UNIX_WiFiPort.h>
#include <TokenRingPort/UNIX_TokenRingPort.h>
#include <PCIPort/UNIX_PCIPort.h>
#include <USBPort/UNIX_USBPort.h>
#include <DisketteDrive/UNIX_DisketteDrive.h>
#include <MagnetoOpticalDrive/UNIX_MagnetoOpticalDrive.h>
#include <DiskDrive/UNIX_DiskDrive.h>
#include <CDROMDrive/UNIX_CDROMDrive.h>
#include <TapeDrive/UNIX_TapeDrive.h>
#include <WORMDrive/UNIX_WORMDrive.h>
#include <DVDDrive/UNIX_DVDDrive.h>
#include <PowerSupply/UNIX_PowerSupply.h>
#include <UninterruptiblePowerSupply/UNIX_UninterruptiblePowerSupply.h>
#include <DiscreteSensor/UNIX_DiscreteSensor.h>
#include <MultiStateSensor/UNIX_MultiStateSensor.h>
#include <TemperatureSensor/UNIX_TemperatureSensor.h>
#include <VoltageSensor/UNIX_VoltageSensor.h>
#include <CurrentSensor/UNIX_CurrentSensor.h>
#include <Tachometer/UNIX_Tachometer.h>
#include <BinarySensor/UNIX_BinarySensor.h>
#include <USBDevice/UNIX_USBDevice.h>
#include <USBHub/UNIX_USBHub.h>
#include <LimitedAccessPort/UNIX_LimitedAccessPort.h>
#include <PickerElement/UNIX_PickerElement.h>
#include <InterLibraryPort/UNIX_InterLibraryPort.h>
#include <ChangerDevice/UNIX_ChangerDevice.h>
#include <Door/UNIX_Door.h>
#include <PCIBridge/UNIX_PCIBridge.h>
#include <PCIeSwitch/UNIX_PCIeSwitch.h>
#include <PCVideoController/UNIX_PCVideoController.h>
#include <AGPVideoController/UNIX_AGPVideoController.h>
#include <ManagementController/UNIX_ManagementController.h>
#include <DisplayController/UNIX_DisplayController.h>
#include <PCMCIAController/UNIX_PCMCIAController.h>
#include <PortController/UNIX_PortController.h>
#include <SerialController/UNIX_SerialController.h>
#include <ESCONController/UNIX_ESCONController.h>
#include <SSAController/UNIX_SSAController.h>
#include <ParallelController/UNIX_ParallelController.h>
#include <SCSIController/UNIX_SCSIController.h>
#include <InfraredController/UNIX_InfraredController.h>
#include <USBController/UNIX_USBController.h>
#include <IDEController/UNIX_IDEController.h>
#include <Battery/UNIX_Battery.h>
#include <Printer/UNIX_Printer.h>
#include <AlarmDevice/UNIX_AlarmDevice.h>
#include <StorageVolume/UNIX_StorageVolume.h>
#include <VolumeSet/UNIX_VolumeSet.h>
#include <LogicalDisk/UNIX_LogicalDisk.h>
#include <PhysicalExtent/UNIX_PhysicalExtent.h>
#include <VolatileStorage/UNIX_VolatileStorage.h>
#include <NonVolatileStorage/UNIX_NonVolatileStorage.h>
#include <CacheMemory/UNIX_CacheMemory.h>
#include <DatabaseSegment/UNIX_DatabaseSegment.h>
#include <OpaqueManagementData/UNIX_OpaqueManagementData.h>
#include <AggregatePSExtent/UNIX_AggregatePSExtent.h>
#include <Snapshot/UNIX_Snapshot.h>
#include <AggregatePExtent/UNIX_AggregatePExtent.h>
#include <TapePartition/UNIX_TapePartition.h>
#include <DiskPartition/UNIX_DiskPartition.h>
#include <CompositeExtent/UNIX_CompositeExtent.h>
#include <ProtectedSpaceExtent/UNIX_ProtectedSpaceExtent.h>
#include <Watchdog/UNIX_Watchdog.h>
#include <IndicatorLED/UNIX_IndicatorLED.h>
#include <Processor/UNIX_Processor.h>
#include <FibreChannelAdapter/UNIX_FibreChannelAdapter.h>
#include <TokenRingAdapter/UNIX_TokenRingAdapter.h>
#include <EthernetAdapter/UNIX_EthernetAdapter.h>
#include <VideoHead/UNIX_VideoHead.h>
#include <KVMRedirectionSAP/UNIX_KVMRedirectionSAP.h>
#include <CredentialManagementSAP/UNIX_CredentialManagementSAP.h>
#include <IPNetworkConnection/UNIX_IPNetworkConnection.h>
#include <PrintSAP/UNIX_PrintSAP.h>
#include <USBRedirectionSAP/UNIX_USBRedirectionSAP.h>
#include <TextRedirectionSAP/UNIX_TextRedirectionSAP.h>
#include <VLAN/UNIX_VLAN.h>
#include <BootSAP/UNIX_BootSAP.h>
#include <ClusteringSAP/UNIX_ClusteringSAP.h>
#include <ServiceAccessURI/UNIX_ServiceAccessURI.h>
#include <LaunchInContextSAP/UNIX_LaunchInContextSAP.h>
#include <RemotePort/UNIX_RemotePort.h>
#include <MediaRedirectionSAP/UNIX_MediaRedirectionSAP.h>
#include <ObjectManagerCommunicationMechanism/UNIX_ObjectManagerCommunicationMechanism.h>
#include <CIMXMLCommunicationMechanism/UNIX_CIMXMLCommunicationMechanism.h>
#include <VLANEndpoint/UNIX_VLANEndpoint.h>
#include <SwitchPort/UNIX_SwitchPort.h>
#include <IPXProtocolEndpoint/UNIX_IPXProtocolEndpoint.h>
#include <CLPProtocolEndpoint/UNIX_CLPProtocolEndpoint.h>
#include <SSHProtocolEndpoint/UNIX_SSHProtocolEndpoint.h>
#include <BGPProtocolEndpoint/UNIX_BGPProtocolEndpoint.h>
#include <DNSProtocolEndpoint/UNIX_DNSProtocolEndpoint.h>
#include <IPProtocolEndpoint/UNIX_IPProtocolEndpoint.h>
#include <DHCPProtocolEndpoint/UNIX_DHCPProtocolEndpoint.h>
#include <LANEndpoint/UNIX_LANEndpoint.h>
#include <WiFiEndpoint/UNIX_WiFiEndpoint.h>
#include <IKESAEndpoint/UNIX_IKESAEndpoint.h>
#include <IPsecSAEndpoint/UNIX_IPsecSAEndpoint.h>
#include <SCSIProtocolEndpoint/UNIX_SCSIProtocolEndpoint.h>
#include <iSCSIProtocolEndpoint/UNIX_iSCSIProtocolEndpoint.h>
#include <TCPProtocolEndpoint/UNIX_TCPProtocolEndpoint.h>
#include <OSPFVirtualInterface/UNIX_OSPFVirtualInterface.h>
#include <OSPFProtocolEndpoint/UNIX_OSPFProtocolEndpoint.h>
#include <UDPProtocolEndpoint/UNIX_UDPProtocolEndpoint.h>
#include <iSCSIConnection/UNIX_iSCSIConnection.h>
#include <iSCSISession/UNIX_iSCSISession.h>
#include <ProcessorCore/UNIX_ProcessorCore.h>
#include <HardwareThread/UNIX_HardwareThread.h>
#include <ResourcePoolConfigurationService/UNIX_ResourcePoolConfigurationService.h>
#include <PrintService/UNIX_PrintService.h>
#include <ControllerConfigurationService/UNIX_ControllerConfigurationService.h>
#include <ZoneService/UNIX_ZoneService.h>
#include <ProtocolService/UNIX_ProtocolService.h>
#include <VirtualSystemManagementService/UNIX_VirtualSystemManagementService.h>
#include <LaunchInContextService/UNIX_LaunchInContextService.h>
#include <DropThresholdCalculationService/UNIX_DropThresholdCalculationService.h>
#include <IBSubnetManager/UNIX_IBSubnetManager.h>
#include <REDDropperService/UNIX_REDDropperService.h>
#include <WeightedREDDropperService/UNIX_WeightedREDDropperService.h>
#include <HeadTailDropper/UNIX_HeadTailDropper.h>
#include <QueuingService/UNIX_QueuingService.h>
#include <PacketSchedulingService/UNIX_PacketSchedulingService.h>
#include <NonWorkConservingSchedulingService/UNIX_NonWorkConservingSchedulingService.h>
#include <ToSMarkerService/UNIX_ToSMarkerService.h>
#include <Priority8021QMarkerService/UNIX_Priority8021QMarkerService.h>
#include <PreambleMarkerService/UNIX_PreambleMarkerService.h>
#include <DSCPMarkerService/UNIX_DSCPMarkerService.h>
#include <ClassifierService/UNIX_ClassifierService.h>
#include <ClassifierElement/UNIX_ClassifierElement.h>
#include <TokenBucketMeterService/UNIX_TokenBucketMeterService.h>
#include <EWMAMeterService/UNIX_EWMAMeterService.h>
#include <AverageRateMeterService/UNIX_AverageRateMeterService.h>
#include <PowerManagementService/UNIX_PowerManagementService.h>
#include <BIOSService/UNIX_BIOSService.h>
#include <EFService/UNIX_EFService.h>
#include <AFService/UNIX_AFService.h>
#include <FlowService/UNIX_FlowService.h>
#include <Hdr8021PService/UNIX_Hdr8021PService.h>
#include <PrecedenceService/UNIX_PrecedenceService.h>
#include <HelpService/UNIX_HelpService.h>
#include <SCSIPathConfigurationService/UNIX_SCSIPathConfigurationService.h>
#include <SourceRoutingService/UNIX_SourceRoutingService.h>
#include <SpanningTreeService/UNIX_SpanningTreeService.h>
#include <TransparentBridgingService/UNIX_TransparentBridgingService.h>
#include <SwitchService/UNIX_SwitchService.h>
#include <BGPService/UNIX_BGPService.h>
#include <OSPFService/UNIX_OSPFService.h>
#include <SharedDeviceManagementService/UNIX_SharedDeviceManagementService.h>
#include <VirtualSystemSnapshotService/UNIX_VirtualSystemSnapshotService.h>
#include <OOBAlertService/UNIX_OOBAlertService.h>
#include <USBRedirectionService/UNIX_USBRedirectionService.h>
#include <TextRedirectionService/UNIX_TextRedirectionService.h>
#include <ObjectManager/UNIX_ObjectManager.h>
#include <ProtocolAdapter/UNIX_ProtocolAdapter.h>
#include <ObjectManagerAdapter/UNIX_ObjectManagerAdapter.h>
#include <FibreProtocolService/UNIX_FibreProtocolService.h>
#include <AccountManagementService/UNIX_AccountManagementService.h>
#include <VerificationService/UNIX_VerificationService.h>
#include <IdentityManagementService/UNIX_IdentityManagementService.h>
#include <StorageHardwareIDManagementService/UNIX_StorageHardwareIDManagementService.h>
#include <CertificateAuthority/UNIX_CertificateAuthority.h>
#include <SharedSecretService/UNIX_SharedSecretService.h>
#include <PublicKeyManagementService/UNIX_PublicKeyManagementService.h>
#include <KeyBasedCredentialManagementService/UNIX_KeyBasedCredentialManagementService.h>
#include <CertificateManagementService/UNIX_CertificateManagementService.h>
#include <Notary/UNIX_Notary.h>
#include <KerberosKeyDistributionCenter/UNIX_KerberosKeyDistributionCenter.h>
#include <AuthorizationService/UNIX_AuthorizationService.h>
#include <PrivilegeManagementService/UNIX_PrivilegeManagementService.h>
#include <RoleBasedAuthorizationService/UNIX_RoleBasedAuthorizationService.h>
#include <PlatformWatchdogService/UNIX_PlatformWatchdogService.h>
#include <ClusteringService/UNIX_ClusteringService.h>
#include <MetricService/UNIX_MetricService.h>
#include <StorageConfigurationService/UNIX_StorageConfigurationService.h>
#include <ConfigurationReportingService/UNIX_ConfigurationReportingService.h>
#include <IPConfigurationService/UNIX_IPConfigurationService.h>
#include <IndicationService/UNIX_IndicationService.h>
#include <SoftwareInstallationService/UNIX_SoftwareInstallationService.h>
#include <DiagnosticService/UNIX_DiagnosticService.h>
#include <DiagnosticTest/UNIX_DiagnosticTest.h>
#include <TimeService/UNIX_TimeService.h>
#include <PowerUtilizationManagementService/UNIX_PowerUtilizationManagementService.h>
#include <StatisticsService/UNIX_StatisticsService.h>
#include <BlockStatisticsService/UNIX_BlockStatisticsService.h>
#include <VLANService/UNIX_VLANService.h>
#include <Specific802dot1QVLANService/UNIX_Specific802dot1QVLANService.h>
#include <WakeUpService/UNIX_WakeUpService.h>
#include <OpaqueManagementDataService/UNIX_OpaqueManagementDataService.h>
#include <DatabaseService/UNIX_DatabaseService.h>
#include <BootService/UNIX_BootService.h>
#include <NetworkPortConfigurationService/UNIX_NetworkPortConfigurationService.h>
#include <WiFiPortConfigurationService/UNIX_WiFiPortConfigurationService.h>
#include <PrintMarker/UNIX_PrintMarker.h>
#include <PrintSupply/UNIX_PrintSupply.h>
#include <PrintInterpreter/UNIX_PrintInterpreter.h>
#include <PrintInputTray/UNIX_PrintInputTray.h>
#include <RoutingPolicy/UNIX_RoutingPolicy.h>
#include <X509CredentialFilterEntry/UNIX_X509CredentialFilterEntry.h>
#include <FilterEntry/UNIX_FilterEntry.h>
#include <PreambleFilter/UNIX_PreambleFilter.h>
#include <PeerIDPayloadFilterEntry/UNIX_PeerIDPayloadFilterEntry.h>
#include <Hdr8021Filter/UNIX_Hdr8021Filter.h>
#include <IPSOFilterEntry/UNIX_IPSOFilterEntry.h>
#include <IPHeadersFilter/UNIX_IPHeadersFilter.h>
#include <StaticForwardingEntry/UNIX_StaticForwardingEntry.h>
#include <SoftwareIdentity/UNIX_SoftwareIdentity.h>
#include <SoftwareElement/UNIX_SoftwareElement.h>
#include <VideoBIOSElement/UNIX_VideoBIOSElement.h>
#include <BIOSElement/UNIX_BIOSElement.h>
#include <ResourcePool/UNIX_ResourcePool.h>
#include <BGPIPRoute/UNIX_BGPIPRoute.h>
#include <AdministrativeDistance/UNIX_AdministrativeDistance.h>
#include <DynamicForwardingEntry/UNIX_DynamicForwardingEntry.h>
#include <SpareGroup/UNIX_SpareGroup.h>
#include <StorageRedundancyGroup/UNIX_StorageRedundancyGroup.h>
#include <ExtraCapacityGroup/UNIX_ExtraCapacityGroup.h>
#include <BGPAttributes/UNIX_BGPAttributes.h>
#include <FilterList/UNIX_FilterList.h>
#include <SoftwareFeature/UNIX_SoftwareFeature.h>
#include <BIOSFeature/UNIX_BIOSFeature.h>
#include <AGPSoftwareFeature/UNIX_AGPSoftwareFeature.h>
#include <VideoBIOSFeature/UNIX_VideoBIOSFeature.h>
#include <OSPFAreaConfiguration/UNIX_OSPFAreaConfiguration.h>
#include <OtherRoleInformation/UNIX_OtherRoleInformation.h>
#include <OtherPersonInformation/UNIX_OtherPersonInformation.h>
#include <Location/UNIX_Location.h>
#include <TraceLevelType/UNIX_TraceLevelType.h>
#include <AggregationMetricDefinition/UNIX_AggregationMetricDefinition.h>
#include <MetricDefinition/UNIX_MetricDefinition.h>
#include <ListenerDestinationWSManagement/UNIX_ListenerDestinationWSManagement.h>
#include <IndicationHandlerCIMXML/UNIX_IndicationHandlerCIMXML.h>
#include <ListenerDestinationCIMXML/UNIX_ListenerDestinationCIMXML.h>
#include <SystemIdentification/UNIX_SystemIdentification.h>
#include <BlockStatisticsManifest/UNIX_BlockStatisticsManifest.h>
#include <IKEProposal/UNIX_IKEProposal.h>
#include <IPsecProposal/UNIX_IPsecProposal.h>
#include <DatabaseParameter/UNIX_DatabaseParameter.h>
#include <DatabaseSegmentSettingData/UNIX_DatabaseSegmentSettingData.h>
#include <IPCOMPTransform/UNIX_IPCOMPTransform.h>
#include <ESPTransform/UNIX_ESPTransform.h>
#include <AHTransform/UNIX_AHTransform.h>
#include <FileSystemSettingData/UNIX_FileSystemSettingData.h>
#include <ExtendedStaticIPAssignmentSettingData/UNIX_ExtendedStaticIPAssignmentSettingData.h>
#include <DHCPSettingData/UNIX_DHCPSettingData.h>
#include <DNSGeneralSettingData/UNIX_DNSGeneralSettingData.h>
#include <DNSSettingData/UNIX_DNSSettingData.h>
#include <StaticIPAssignmentSettingData/UNIX_StaticIPAssignmentSettingData.h>
#include <iSCSISessionSettings/UNIX_iSCSISessionSettings.h>
#include <DiagnosticSettingData/UNIX_DiagnosticSettingData.h>
#include <StatisticalSetting/UNIX_StatisticalSetting.h>
#include <StorageSetting/UNIX_StorageSetting.h>
#include <StorageSettingWithHints/UNIX_StorageSettingWithHints.h>
#include <EthernetPortAllocationSettingData/UNIX_EthernetPortAllocationSettingData.h>
#include <ProcessorAllocationSettingData/UNIX_ProcessorAllocationSettingData.h>
#include <PowerAllocationSettingData/UNIX_PowerAllocationSettingData.h>
#include <StorageAllocationSettingData/UNIX_StorageAllocationSettingData.h>
#include <BootConfigSetting/UNIX_BootConfigSetting.h>
#include <SSHSettingData/UNIX_SSHSettingData.h>
#include <IndicationServiceSettingData/UNIX_IndicationServiceSettingData.h>
#include <VirtualSystemSettingData/UNIX_VirtualSystemSettingData.h>
#include <VirtualEthernetSwitchSettingData/UNIX_VirtualEthernetSwitchSettingData.h>
#include <IEEE8021xSettings/UNIX_IEEE8021xSettings.h>
#include <VLANEndpointSettingData/UNIX_VLANEndpointSettingData.h>
#include <LogicalPortSettings/UNIX_LogicalPortSettings.h>
#include <StorageClientSettingData/UNIX_StorageClientSettingData.h>
#include <VirtualSystemMigrationSettingData/UNIX_VirtualSystemMigrationSettingData.h>
#include <VideoHeadResolution/UNIX_VideoHeadResolution.h>
#include <BootSettingData/UNIX_BootSettingData.h>
#include <CLPSettingData/UNIX_CLPSettingData.h>
#include <WiFiNetworkDetectionSettings/UNIX_WiFiNetworkDetectionSettings.h>
#include <SCSIMultipathSettings/UNIX_SCSIMultipathSettings.h>
#include <CommonDatabaseSettingData/UNIX_CommonDatabaseSettingData.h>
#include <WiFiEndpointSettings/UNIX_WiFiEndpointSettings.h>
#include <iSCSIConnectionSettings/UNIX_iSCSIConnectionSettings.h>
#include <AccountSettingData/UNIX_AccountSettingData.h>
#include <ConnectivityMembershipSettingData/UNIX_ConnectivityMembershipSettingData.h>
#include <ZoneMembershipSettingData/UNIX_ZoneMembershipSettingData.h>
#include <BootSourceSetting/UNIX_BootSourceSetting.h>
#include <SAEndpointRefreshSettings/UNIX_SAEndpointRefreshSettings.h>
#include <IPVersionSettingData/UNIX_IPVersionSettingData.h>
#include <JobSettingData/UNIX_JobSettingData.h>
#include <FCSwitchSettings/UNIX_FCSwitchSettings.h>
#include <IndicationFilter/UNIX_IndicationFilter.h>
#include <OtherOrgUnitInformation/UNIX_OtherOrgUnitInformation.h>
#include <MethodParameters/UNIX_MethodParameters.h>
#include <ConfigurationCapacity/UNIX_ConfigurationCapacity.h>
#include <MemoryCapacity/UNIX_MemoryCapacity.h>
#include <KerberosCredential/UNIX_KerberosCredential.h>
#include <KerberosTicket/UNIX_KerberosTicket.h>
#include <NamedCredential/UNIX_NamedCredential.h>
#include <PublicKeyCertificate/UNIX_PublicKeyCertificate.h>
#include <X509CRL/UNIX_X509CRL.h>
#include <X509Certificate/UNIX_X509Certificate.h>
#include <NamedSharedIKESecret/UNIX_NamedSharedIKESecret.h>
#include <SharedSecret/UNIX_SharedSecret.h>
#include <UnsignedPublicKey/UNIX_UnsignedPublicKey.h>
#include <SharedCredential/UNIX_SharedCredential.h>
#include <UnsignedCredential/UNIX_UnsignedCredential.h>
#include <MediaAccessStatData/UNIX_MediaAccessStatData.h>
#include <PickerStatData/UNIX_PickerStatData.h>
#include <DatabaseServiceStatistics/UNIX_DatabaseServiceStatistics.h>
#include <FCPortStatistics/UNIX_FCPortStatistics.h>
#include <TokenRingPortStatistics/UNIX_TokenRingPortStatistics.h>
#include <EthernetPortStatistics/UNIX_EthernetPortStatistics.h>
#include <LLDPEthernetPortStatistics/UNIX_LLDPEthernetPortStatistics.h>
#include <BlockStorageStatisticalData/UNIX_BlockStorageStatisticalData.h>
#include <SAEndpointConnectionStatistics/UNIX_SAEndpointConnectionStatistics.h>
#include <iSCSILoginStatistics/UNIX_iSCSILoginStatistics.h>
#include <iSCSISessionFailures/UNIX_iSCSISessionFailures.h>
#include <FCPortRateStatistics/UNIX_FCPortRateStatistics.h>
#include <MediaPhysicalStatData/UNIX_MediaPhysicalStatData.h>
#include <DatabaseResourceStatistics/UNIX_DatabaseResourceStatistics.h>
#include <StatisticalRuntimeOverview/UNIX_StatisticalRuntimeOverview.h>
#include <DeviceErrorData/UNIX_DeviceErrorData.h>
#include <BGPEndpointStatistics/UNIX_BGPEndpointStatistics.h>
#include <CommonDatabaseStatistics/UNIX_CommonDatabaseStatistics.h>
#include <CIMOMStatisticalData/UNIX_CIMOMStatisticalData.h>
#include <LabelReaderStatData/UNIX_LabelReaderStatData.h>
#include <StorageHardwareID/UNIX_StorageHardwareID.h>
#include <GatewayPathID/UNIX_GatewayPathID.h>
#include <IPNetworkIdentity/UNIX_IPNetworkIdentity.h>
#include <CredentialStore/UNIX_CredentialStore.h>
#include <Keystore/UNIX_Keystore.h>
#include <RangeOfIPAddresses/UNIX_RangeOfIPAddresses.h>
#include <StatisticsCollection/UNIX_StatisticsCollection.h>
#include <BlockStatisticsManifestCollection/UNIX_BlockStatisticsManifestCollection.h>
#include <LogicalPortGroup/UNIX_LogicalPortGroup.h>
#include <PCIPortGroup/UNIX_PCIPortGroup.h>
#include <NamedAddressCollection/UNIX_NamedAddressCollection.h>
#include <ZoneSet/UNIX_ZoneSet.h>
#include <OSPFLink/UNIX_OSPFLink.h>
#include <IPXConnectivityNetwork/UNIX_IPXConnectivityNetwork.h>
#include <LANConnectivitySegment/UNIX_LANConnectivitySegment.h>
#include <IPConnectivitySubnet/UNIX_IPConnectivitySubnet.h>
#include <Zone/UNIX_Zone.h>
#include <NetworkVLAN/UNIX_NetworkVLAN.h>
#include <PolicyRoleCollection/UNIX_PolicyRoleCollection.h>
#include <RedundancySet/UNIX_RedundancySet.h>
#include <StorageRedundancySet/UNIX_StorageRedundancySet.h>
#include <SCSITargetPortGroup/UNIX_SCSITargetPortGroup.h>
#include <Profile/UNIX_Profile.h>
#include <Group/UNIX_Group.h>
#include <FilterCollection/UNIX_FilterCollection.h>
#include <ReplacementSet/UNIX_ReplacementSet.h>
#include <Role/UNIX_Role.h>
#include <InstalledProduct/UNIX_InstalledProduct.h>
#include <ConcreteCollection/UNIX_ConcreteCollection.h>
#include <BGPCluster/UNIX_BGPCluster.h>
#include <DiskGroup/UNIX_DiskGroup.h>
#include <LANSegment/UNIX_LANSegment.h>
#include <IPXNetwork/UNIX_IPXNetwork.h>
#include <IPSubnet/UNIX_IPSubnet.h>
#include <BufferPool/UNIX_BufferPool.h>
#include <BGPPeerGroup/UNIX_BGPPeerGroup.h>
#include <IPAddressRange/UNIX_IPAddressRange.h>
#include <BIOSString/UNIX_BIOSString.h>
#include <BIOSInteger/UNIX_BIOSInteger.h>
#include <BIOSPassword/UNIX_BIOSPassword.h>
#include <BIOSEnumeration/UNIX_BIOSEnumeration.h>
#include <MethodResult/UNIX_MethodResult.h>
#include <UsersAccess/UNIX_UsersAccess.h>
#include <UserContact/UNIX_UserContact.h>
#include <Person/UNIX_Person.h>
#include <Organization/UNIX_Organization.h>
#include <OrgUnit/UNIX_OrgUnit.h>
#include <SecuritySensitivity/UNIX_SecuritySensitivity.h>
#include <PhysicalStatisticalInformation/UNIX_PhysicalStatisticalInformation.h>
#include <MediaPhysicalStatInfo/UNIX_MediaPhysicalStatInfo.h>
#include <LabelReaderStatInfo/UNIX_LabelReaderStatInfo.h>
#include <FCAdapterEventCounters/UNIX_FCAdapterEventCounters.h>
#include <FibrePortEventCounters/UNIX_FibrePortEventCounters.h>
#include <PickerStatInfo/UNIX_PickerStatInfo.h>
#include <MediaAccessStatInfo/UNIX_MediaAccessStatInfo.h>
#include <SystemStatisticalInformation/UNIX_SystemStatisticalInformation.h>
#include <DeviceErrorCounts/UNIX_DeviceErrorCounts.h>
#include <SpanningTreeStatistics/UNIX_SpanningTreeStatistics.h>
#include <TransparentBridgingStatistics/UNIX_TransparentBridgingStatistics.h>
#include <BGPStatistics/UNIX_BGPStatistics.h>
#include <SwitchPortStatistics/UNIX_SwitchPortStatistics.h>
#include <SwitchPortTransparentBridgingStatistics/UNIX_SwitchPortTransparentBridgingStatistics.h>
#include <SwitchPortSourceRoutingStatistics/UNIX_SwitchPortSourceRoutingStatistics.h>
#include <SwitchPortSpanningTreeStatistics/UNIX_SwitchPortSpanningTreeStatistics.h>
#include <ProcessStatisticalInformation/UNIX_ProcessStatisticalInformation.h>
#include <DiagnosticServiceRecord/UNIX_DiagnosticServiceRecord.h>
#include <DiagnosticCompletionRecord/UNIX_DiagnosticCompletionRecord.h>
#include <DiagnosticSettingDataRecord/UNIX_DiagnosticSettingDataRecord.h>
#include <DiagnosticSettingRecord/UNIX_DiagnosticSettingRecord.h>
#include <LogRecord/UNIX_LogRecord.h>
#include <LogEntry/UNIX_LogEntry.h>
#include <PrioritySchedulingElement/UNIX_PrioritySchedulingElement.h>
#include <BoundedPrioritySchedulingElement/UNIX_BoundedPrioritySchedulingElement.h>
#include <AllocationSchedulingElement/UNIX_AllocationSchedulingElement.h>
#include <WRRSchedulingElement/UNIX_WRRSchedulingElement.h>
#include <Namespace/UNIX_Namespace.h>
#include <NextHopRoute/UNIX_NextHopRoute.h>
#include <NextHopIPRoute/UNIX_NextHopIPRoute.h>
#include <USBRedirectionCapabilities/UNIX_USBRedirectionCapabilities.h>
#include <MediaRedirectionCapabilities/UNIX_MediaRedirectionCapabilities.h>
#include <BootServiceCapabilities/UNIX_BootServiceCapabilities.h>
#include <OpaqueManagementDataCapabilities/UNIX_OpaqueManagementDataCapabilities.h>
#include <PlatformWatchdogServiceCapabilities/UNIX_PlatformWatchdogServiceCapabilities.h>
#include <AlarmDeviceCapabilities/UNIX_AlarmDeviceCapabilities.h>
#include <FCSwitchCapabilities/UNIX_FCSwitchCapabilities.h>
#include <IndicatorLEDCapabilities/UNIX_IndicatorLEDCapabilities.h>
#include <RecordLogCapabilities/UNIX_RecordLogCapabilities.h>
#include <MetricServiceCapabilities/UNIX_MetricServiceCapabilities.h>
#include <DHCPCapabilities/UNIX_DHCPCapabilities.h>
#include <OperatingSystemCapabilities/UNIX_OperatingSystemCapabilities.h>
#include <WiFiEndpointCapabilities/UNIX_WiFiEndpointCapabilities.h>
#include <NetworkPortCapabilities/UNIX_NetworkPortCapabilities.h>
#include <WiFiPortCapabilities/UNIX_WiFiPortCapabilities.h>
#include <FCPortCapabilities/UNIX_FCPortCapabilities.h>
#include <VirtualSystemManagementCapabilities/UNIX_VirtualSystemManagementCapabilities.h>
#include <ProcessorCapabilities/UNIX_ProcessorCapabilities.h>
#include <LaunchInContextCapabilities/UNIX_LaunchInContextCapabilities.h>
#include <AccountManagementCapabilities/UNIX_AccountManagementCapabilities.h>
#include <CLPCapabilities/UNIX_CLPCapabilities.h>
#include <SSHCapabilities/UNIX_SSHCapabilities.h>
#include <PowerUtilizationManagementCapabilities/UNIX_PowerUtilizationManagementCapabilities.h>
#include <CredentialManagementCapabilities/UNIX_CredentialManagementCapabilities.h>
#include <CertificateManagementCapabilities/UNIX_CertificateManagementCapabilities.h>
#include <VLANEndpointCapabilities/UNIX_VLANEndpointCapabilities.h>
#include <QueryCapabilities/UNIX_QueryCapabilities.h>
#include <StorageReplicationCapabilities/UNIX_StorageReplicationCapabilities.h>
#include <IEEE8021xCapabilities/UNIX_IEEE8021xCapabilities.h>
#include <CommonDatabaseCapabilities/UNIX_CommonDatabaseCapabilities.h>
#include <BIOSServiceCapabilities/UNIX_BIOSServiceCapabilities.h>
#include <StorageCapabilities/UNIX_StorageCapabilities.h>
#include <OSPFServiceCapabilities/UNIX_OSPFServiceCapabilities.h>
#include <ComputerSystemNodeCapabilities/UNIX_ComputerSystemNodeCapabilities.h>
#include <StatisticsCapabilities/UNIX_StatisticsCapabilities.h>
#include <BlockStatisticsCapabilities/UNIX_BlockStatisticsCapabilities.h>
#include <PhysicalAssetCapabilities/UNIX_PhysicalAssetCapabilities.h>
#include <DeviceSharingCapabilities/UNIX_DeviceSharingCapabilities.h>
#include <IndicationServiceCapabilities/UNIX_IndicationServiceCapabilities.h>
#include <AllocationCapabilities/UNIX_AllocationCapabilities.h>
#include <LocalizationCapabilities/UNIX_LocalizationCapabilities.h>
#include <SoftwareInstallationServiceCapabilities/UNIX_SoftwareInstallationServiceCapabilities.h>
#include <VirtualSystemSnapshotServiceCapabilities/UNIX_VirtualSystemSnapshotServiceCapabilities.h>
#include <SCSIMultipathConfigurationCapabilities/UNIX_SCSIMultipathConfigurationCapabilities.h>
#include <ZoneCapabilities/UNIX_ZoneCapabilities.h>
#include <iSCSICapabilities/UNIX_iSCSICapabilities.h>
#include <PowerManagementCapabilities/UNIX_PowerManagementCapabilities.h>
#include <DiagnosticServiceCapabilities/UNIX_DiagnosticServiceCapabilities.h>
#include <FileSystemCapabilities/UNIX_FileSystemCapabilities.h>
#include <VirtualSystemSnapshotCapabilities/UNIX_VirtualSystemSnapshotCapabilities.h>
#include <ResourcePoolConfigurationCapabilities/UNIX_ResourcePoolConfigurationCapabilities.h>
#include <PrivilegeManagementCapabilities/UNIX_PrivilegeManagementCapabilities.h>
#include <RoleBasedManagementCapabilities/UNIX_RoleBasedManagementCapabilities.h>
#include <StorageConfigurationCapabilities/UNIX_StorageConfigurationCapabilities.h>
#include <ProtocolControllerMaskingCapabilities/UNIX_ProtocolControllerMaskingCapabilities.h>
#include <Privilege/UNIX_Privilege.h>
#include <AuthorizedPrivilege/UNIX_AuthorizedPrivilege.h>
#include <OtherOrganizationInformation/UNIX_OtherOrganizationInformation.h>
#include <DirectorySpecification/UNIX_DirectorySpecification.h>
#include <MemoryCheck/UNIX_MemoryCheck.h>
#include <VersionCompatibilityCheck/UNIX_VersionCompatibilityCheck.h>
#include <DiskSpaceCheck/UNIX_DiskSpaceCheck.h>
#include <SoftwareElementVersionCheck/UNIX_SoftwareElementVersionCheck.h>
#include <FileSpecification/UNIX_FileSpecification.h>
#include <ArchitectureCheck/UNIX_ArchitectureCheck.h>
#include <OSVersionCheck/UNIX_OSVersionCheck.h>
#include <SettingCheck/UNIX_SettingCheck.h>
#include <SwapSpaceCheck/UNIX_SwapSpaceCheck.h>
#include <RegisteredSubProfile/UNIX_RegisteredSubProfile.h>
#include <RejectConnectionAction/UNIX_RejectConnectionAction.h>
#include <VendorPolicyAction/UNIX_VendorPolicyAction.h>
#include <NetworkPacketAction/UNIX_NetworkPacketAction.h>
#include <MethodAction/UNIX_MethodAction.h>
#include <CompoundPolicyAction/UNIX_CompoundPolicyAction.h>
#include <IKEAction/UNIX_IKEAction.h>
#include <IPsecTunnelAction/UNIX_IPsecTunnelAction.h>
#include <IPsecTransportAction/UNIX_IPsecTransportAction.h>
#include <PreconfiguredTunnelAction/UNIX_PreconfiguredTunnelAction.h>
#include <PreconfiguredTransportAction/UNIX_PreconfiguredTransportAction.h>
#include <IPsecRule/UNIX_IPsecRule.h>
#include <IKERule/UNIX_IKERule.h>
#include <AuthenticationRule/UNIX_AuthenticationRule.h>
#include <PolicyGroup/UNIX_PolicyGroup.h>
#include <VendorPolicyCondition/UNIX_VendorPolicyCondition.h>
#include <DocumentAuthentication/UNIX_DocumentAuthentication.h>
#include <PublicPrivateKeyAuthentication/UNIX_PublicPrivateKeyAuthentication.h>
#include <KerberosAuthentication/UNIX_KerberosAuthentication.h>
#include <NetworkingIDAuthentication/UNIX_NetworkingIDAuthentication.h>
#include <SharedSecretAuthentication/UNIX_SharedSecretAuthentication.h>
#include <PhysicalCredentialAuthentication/UNIX_PhysicalCredentialAuthentication.h>
#include <AccountAuthentication/UNIX_AccountAuthentication.h>
#include <BiometricAuthentication/UNIX_BiometricAuthentication.h>
#include <PolicyTimePeriodCondition/UNIX_PolicyTimePeriodCondition.h>
#include <QueryCondition/UNIX_QueryCondition.h>
#include <PacketFilterCondition/UNIX_PacketFilterCondition.h>
#include <CompoundPolicyCondition/UNIX_CompoundPolicyCondition.h>
#include <StorageError/UNIX_StorageError.h>
#include <MemoryError/UNIX_MemoryError.h>
#include <Configuration/UNIX_Configuration.h>
#include <RebootAction/UNIX_RebootAction.h>
#include <ExecuteProgram/UNIX_ExecuteProgram.h>
#include <CopyFileAction/UNIX_CopyFileAction.h>
#include <RemoveFileAction/UNIX_RemoveFileAction.h>
#include <ModifySettingAction/UNIX_ModifySettingAction.h>
#include <RemoveDirectoryAction/UNIX_RemoveDirectoryAction.h>
#include <CreateDirectoryAction/UNIX_CreateDirectoryAction.h>
#include <FRU/UNIX_FRU.h>
#include <BaseMetricValue/UNIX_BaseMetricValue.h>
#include <AggregationMetricValue/UNIX_AggregationMetricValue.h>
#include <View/UNIX_View.h>
#include <PhysicalComputerSystemView/UNIX_PhysicalComputerSystemView.h>
#include <SupportAccess/UNIX_SupportAccess.h>
#include <Product/UNIX_Product.h>
#include <SystemConfiguration/UNIX_SystemConfiguration.h>
#include <SystemSetting/UNIX_SystemSetting.h>
#include <VideoControllerResolution/UNIX_VideoControllerResolution.h>
#include <DiagnosticSetting/UNIX_DiagnosticSetting.h>
#include <TimeZone/UNIX_TimeZone.h>
#include <MonitorResolution/UNIX_MonitorResolution.h>
#include <OtherGroupInformation/UNIX_OtherGroupInformation.h>
#include <PhysicalLink/UNIX_PhysicalLink.h>
#include <PhysicalMedia/UNIX_PhysicalMedia.h>
#include <PhysicalTape/UNIX_PhysicalTape.h>
#include <Chip/UNIX_Chip.h>
#include <PhysicalMemory/UNIX_PhysicalMemory.h>
#include <PhysicalConnector/UNIX_PhysicalConnector.h>
#include <Slot/UNIX_Slot.h>
#include <Card/UNIX_Card.h>
#include <SystemBusCard/UNIX_SystemBusCard.h>
#include <Rack/UNIX_Rack.h>
#include <Chassis/UNIX_Chassis.h>
#include <PackageLocation/UNIX_PackageLocation.h>
#include <StorageMediaLocation/UNIX_StorageMediaLocation.h>
#include <Magazine/UNIX_Magazine.h>
#include <AuthenticationRequirement/UNIX_AuthenticationRequirement.h>
#include <BGPRouteMap/UNIX_BGPRouteMap.h>
#include <AccessControlInformation/UNIX_AccessControlInformation.h>
#include <StoragePool/UNIX_StoragePool.h>
#include <ConcreteJob/UNIX_ConcreteJob.h>
#include <PrintJob/UNIX_PrintJob.h>
#include <DataFile/UNIX_DataFile.h>
#include <FIFOPipeFile/UNIX_FIFOPipeFile.h>
#include <DeviceFile/UNIX_DeviceFile.h>
#include <DeviceFile/UNIX_DeviceFile.h>
#include <Directory/UNIX_Directory.h>
#include <UnixDirectory/UNIX_UnixDirectory.h>
#include <SymbolicLink/UNIX_SymbolicLink.h>
#include <BGPPathAttributes/UNIX_BGPPathAttributes.h>
#include <File/UNIX_File.h>
#include <FileSystem/UNIX_FileSystem.h>
#include <RemoteFileSystem/UNIX_RemoteFileSystem.h>
#include <NFS/UNIX_NFS.h>
#include <DatabaseStorageArea/UNIX_DatabaseStorageArea.h>
#include <LocalFileSystem/UNIX_LocalFileSystem.h>
#include <LocalFileSystem/UNIX_LocalFileSystem.h>
#include <ApplicationSystem/UNIX_ApplicationSystem.h>
#include <DatabaseSystem/UNIX_DatabaseSystem.h>
#include <VirtualComputerSystem/UNIX_VirtualComputerSystem.h>
#include <ComputerSystem/UNIX_ComputerSystem.h>
#include <Cluster/UNIX_Cluster.h>
#include <StorageLibrary/UNIX_StorageLibrary.h>
#include <ReusablePolicyContainer/UNIX_ReusablePolicyContainer.h>
#include <RoutingProtocolDomain/UNIX_RoutingProtocolDomain.h>
#include <OSPFArea/UNIX_OSPFArea.h>
#include <Network/UNIX_Network.h>
#include <PolicyRepository/UNIX_PolicyRepository.h>
#include <AutonomousSystem/UNIX_AutonomousSystem.h>
#include <DMA/UNIX_DMA.h>
#include <MemoryResource/UNIX_MemoryResource.h>
#include <PortResource/UNIX_PortResource.h>
#include <IRQ/UNIX_IRQ.h>
#include <Process/UNIX_Process.h>
#include <MessageLog/UNIX_MessageLog.h>
#include <DiagnosticLog/UNIX_DiagnosticLog.h>
#include <DiagnosticsLog/UNIX_DiagnosticsLog.h>
#include <OperatingSystem/UNIX_OperatingSystem.h>
#include <Account/UNIX_Account.h>
#include <JobQueue/UNIX_JobQueue.h>
#include <PrintQueue/UNIX_PrintQueue.h>
#include <Thread/UNIX_Thread.h>
#include <CommonDatabase/UNIX_CommonDatabase.h>
#include <LogicalModule/UNIX_LogicalModule.h>
#include <PassThroughModule/UNIX_PassThroughModule.h>
#include <LabelReader/UNIX_LabelReader.h>
#include <Scanner/UNIX_Scanner.h>
#include <ProtocolController/UNIX_ProtocolController.h>
#include <SCSIProtocolController/UNIX_SCSIProtocolController.h>
#include <WiFiRadio/UNIX_WiFiRadio.h>
#include <HeatPipe/UNIX_HeatPipe.h>
#include <Refrigeration/UNIX_Refrigeration.h>
#include <Fan/UNIX_Fan.h>
#include <PowerSource/UNIX_PowerSource.h>
#include <DesktopMonitor/UNIX_DesktopMonitor.h>
#include <FlatPanel/UNIX_FlatPanel.h>
#include <Keyboard/UNIX_Keyboard.h>
#include <PointingDevice/UNIX_PointingDevice.h>
#include <CableModem/UNIX_CableModem.h>
#include <SDSLModem/UNIX_SDSLModem.h>
#include <HDSLModem/UNIX_HDSLModem.h>
#include <VDSLModem/UNIX_VDSLModem.h>
#include <ADSLModem/UNIX_ADSLModem.h>
#include <POTSModem/UNIX_POTSModem.h>
#include <Unimodem/UNIX_Unimodem.h>
#include <ISDNModem/UNIX_ISDNModem.h>
#include <FibrePort/UNIX_FibrePort.h>
#include <FCPort/UNIX_FCPort.h>
#include <EthernetPort/UNIX_EthernetPort.h>
#include <LLDPEthernetPort/UNIX_LLDPEthernetPort.h>
#include <WiFiPort/UNIX_WiFiPort.h>
#include <TokenRingPort/UNIX_TokenRingPort.h>
#include <PCIPort/UNIX_PCIPort.h>
#include <USBPort/UNIX_USBPort.h>
#include <DisketteDrive/UNIX_DisketteDrive.h>
#include <MagnetoOpticalDrive/UNIX_MagnetoOpticalDrive.h>
#include <DiskDrive/UNIX_DiskDrive.h>
#include <CDROMDrive/UNIX_CDROMDrive.h>
#include <TapeDrive/UNIX_TapeDrive.h>
#include <WORMDrive/UNIX_WORMDrive.h>
#include <DVDDrive/UNIX_DVDDrive.h>
#include <PowerSupply/UNIX_PowerSupply.h>
#include <UninterruptiblePowerSupply/UNIX_UninterruptiblePowerSupply.h>
#include <DiscreteSensor/UNIX_DiscreteSensor.h>
#include <MultiStateSensor/UNIX_MultiStateSensor.h>
#include <TemperatureSensor/UNIX_TemperatureSensor.h>
#include <VoltageSensor/UNIX_VoltageSensor.h>
#include <CurrentSensor/UNIX_CurrentSensor.h>
#include <Tachometer/UNIX_Tachometer.h>
#include <BinarySensor/UNIX_BinarySensor.h>
#include <USBDevice/UNIX_USBDevice.h>
#include <USBHub/UNIX_USBHub.h>
#include <LimitedAccessPort/UNIX_LimitedAccessPort.h>
#include <PickerElement/UNIX_PickerElement.h>
#include <InterLibraryPort/UNIX_InterLibraryPort.h>
#include <ChangerDevice/UNIX_ChangerDevice.h>
#include <Door/UNIX_Door.h>
#include <PCIBridge/UNIX_PCIBridge.h>
#include <PCIeSwitch/UNIX_PCIeSwitch.h>
#include <PCVideoController/UNIX_PCVideoController.h>
#include <AGPVideoController/UNIX_AGPVideoController.h>
#include <ManagementController/UNIX_ManagementController.h>
#include <DisplayController/UNIX_DisplayController.h>
#include <PCMCIAController/UNIX_PCMCIAController.h>
#include <PortController/UNIX_PortController.h>
#include <SerialController/UNIX_SerialController.h>
#include <ESCONController/UNIX_ESCONController.h>
#include <SSAController/UNIX_SSAController.h>
#include <ParallelController/UNIX_ParallelController.h>
#include <SCSIController/UNIX_SCSIController.h>
#include <InfraredController/UNIX_InfraredController.h>
#include <USBController/UNIX_USBController.h>
#include <IDEController/UNIX_IDEController.h>
#include <Battery/UNIX_Battery.h>
#include <Printer/UNIX_Printer.h>
#include <AlarmDevice/UNIX_AlarmDevice.h>
#include <StorageVolume/UNIX_StorageVolume.h>
#include <VolumeSet/UNIX_VolumeSet.h>
#include <LogicalDisk/UNIX_LogicalDisk.h>
#include <PhysicalExtent/UNIX_PhysicalExtent.h>
#include <VolatileStorage/UNIX_VolatileStorage.h>
#include <NonVolatileStorage/UNIX_NonVolatileStorage.h>
#include <CacheMemory/UNIX_CacheMemory.h>
#include <DatabaseSegment/UNIX_DatabaseSegment.h>
#include <OpaqueManagementData/UNIX_OpaqueManagementData.h>
#include <AggregatePSExtent/UNIX_AggregatePSExtent.h>
#include <Snapshot/UNIX_Snapshot.h>
#include <AggregatePExtent/UNIX_AggregatePExtent.h>
#include <TapePartition/UNIX_TapePartition.h>
#include <DiskPartition/UNIX_DiskPartition.h>
#include <CompositeExtent/UNIX_CompositeExtent.h>
#include <ProtectedSpaceExtent/UNIX_ProtectedSpaceExtent.h>
#include <Watchdog/UNIX_Watchdog.h>
#include <IndicatorLED/UNIX_IndicatorLED.h>
#include <Processor/UNIX_Processor.h>
#include <FibreChannelAdapter/UNIX_FibreChannelAdapter.h>
#include <TokenRingAdapter/UNIX_TokenRingAdapter.h>
#include <EthernetAdapter/UNIX_EthernetAdapter.h>
#include <VideoHead/UNIX_VideoHead.h>
#include <KVMRedirectionSAP/UNIX_KVMRedirectionSAP.h>
#include <CredentialManagementSAP/UNIX_CredentialManagementSAP.h>
#include <IPNetworkConnection/UNIX_IPNetworkConnection.h>
#include <PrintSAP/UNIX_PrintSAP.h>
#include <USBRedirectionSAP/UNIX_USBRedirectionSAP.h>
#include <TextRedirectionSAP/UNIX_TextRedirectionSAP.h>
#include <VLAN/UNIX_VLAN.h>
#include <BootSAP/UNIX_BootSAP.h>
#include <ClusteringSAP/UNIX_ClusteringSAP.h>
#include <ServiceAccessURI/UNIX_ServiceAccessURI.h>
#include <LaunchInContextSAP/UNIX_LaunchInContextSAP.h>
#include <RemotePort/UNIX_RemotePort.h>
#include <MediaRedirectionSAP/UNIX_MediaRedirectionSAP.h>
#include <ObjectManagerCommunicationMechanism/UNIX_ObjectManagerCommunicationMechanism.h>
#include <CIMXMLCommunicationMechanism/UNIX_CIMXMLCommunicationMechanism.h>
#include <VLANEndpoint/UNIX_VLANEndpoint.h>
#include <SwitchPort/UNIX_SwitchPort.h>
#include <IPXProtocolEndpoint/UNIX_IPXProtocolEndpoint.h>
#include <CLPProtocolEndpoint/UNIX_CLPProtocolEndpoint.h>
#include <SSHProtocolEndpoint/UNIX_SSHProtocolEndpoint.h>
#include <BGPProtocolEndpoint/UNIX_BGPProtocolEndpoint.h>
#include <DNSProtocolEndpoint/UNIX_DNSProtocolEndpoint.h>
#include <IPProtocolEndpoint/UNIX_IPProtocolEndpoint.h>
#include <DHCPProtocolEndpoint/UNIX_DHCPProtocolEndpoint.h>
#include <LANEndpoint/UNIX_LANEndpoint.h>
#include <WiFiEndpoint/UNIX_WiFiEndpoint.h>
#include <IKESAEndpoint/UNIX_IKESAEndpoint.h>
#include <IPsecSAEndpoint/UNIX_IPsecSAEndpoint.h>
#include <SCSIProtocolEndpoint/UNIX_SCSIProtocolEndpoint.h>
#include <iSCSIProtocolEndpoint/UNIX_iSCSIProtocolEndpoint.h>
#include <TCPProtocolEndpoint/UNIX_TCPProtocolEndpoint.h>
#include <OSPFVirtualInterface/UNIX_OSPFVirtualInterface.h>
#include <OSPFProtocolEndpoint/UNIX_OSPFProtocolEndpoint.h>
#include <UDPProtocolEndpoint/UNIX_UDPProtocolEndpoint.h>
#include <iSCSIConnection/UNIX_iSCSIConnection.h>
#include <iSCSISession/UNIX_iSCSISession.h>
#include <ProcessorCore/UNIX_ProcessorCore.h>
#include <HardwareThread/UNIX_HardwareThread.h>
#include <ResourcePoolConfigurationService/UNIX_ResourcePoolConfigurationService.h>
#include <PrintService/UNIX_PrintService.h>
#include <ControllerConfigurationService/UNIX_ControllerConfigurationService.h>
#include <ZoneService/UNIX_ZoneService.h>
#include <ProtocolService/UNIX_ProtocolService.h>
#include <VirtualSystemManagementService/UNIX_VirtualSystemManagementService.h>
#include <LaunchInContextService/UNIX_LaunchInContextService.h>
#include <DropThresholdCalculationService/UNIX_DropThresholdCalculationService.h>
#include <IBSubnetManager/UNIX_IBSubnetManager.h>
#include <REDDropperService/UNIX_REDDropperService.h>
#include <WeightedREDDropperService/UNIX_WeightedREDDropperService.h>
#include <HeadTailDropper/UNIX_HeadTailDropper.h>
#include <QueuingService/UNIX_QueuingService.h>
#include <PacketSchedulingService/UNIX_PacketSchedulingService.h>
#include <NonWorkConservingSchedulingService/UNIX_NonWorkConservingSchedulingService.h>
#include <ToSMarkerService/UNIX_ToSMarkerService.h>
#include <Priority8021QMarkerService/UNIX_Priority8021QMarkerService.h>
#include <PreambleMarkerService/UNIX_PreambleMarkerService.h>
#include <DSCPMarkerService/UNIX_DSCPMarkerService.h>
#include <ClassifierService/UNIX_ClassifierService.h>
#include <ClassifierElement/UNIX_ClassifierElement.h>
#include <TokenBucketMeterService/UNIX_TokenBucketMeterService.h>
#include <EWMAMeterService/UNIX_EWMAMeterService.h>
#include <AverageRateMeterService/UNIX_AverageRateMeterService.h>
#include <PowerManagementService/UNIX_PowerManagementService.h>
#include <BIOSService/UNIX_BIOSService.h>
#include <EFService/UNIX_EFService.h>
#include <AFService/UNIX_AFService.h>
#include <FlowService/UNIX_FlowService.h>
#include <Hdr8021PService/UNIX_Hdr8021PService.h>
#include <PrecedenceService/UNIX_PrecedenceService.h>
#include <HelpService/UNIX_HelpService.h>
#include <SCSIPathConfigurationService/UNIX_SCSIPathConfigurationService.h>
#include <SourceRoutingService/UNIX_SourceRoutingService.h>
#include <SpanningTreeService/UNIX_SpanningTreeService.h>
#include <TransparentBridgingService/UNIX_TransparentBridgingService.h>
#include <SwitchService/UNIX_SwitchService.h>
#include <BGPService/UNIX_BGPService.h>
#include <OSPFService/UNIX_OSPFService.h>
#include <SharedDeviceManagementService/UNIX_SharedDeviceManagementService.h>
#include <VirtualSystemSnapshotService/UNIX_VirtualSystemSnapshotService.h>
#include <OOBAlertService/UNIX_OOBAlertService.h>
#include <USBRedirectionService/UNIX_USBRedirectionService.h>
#include <TextRedirectionService/UNIX_TextRedirectionService.h>
#include <ObjectManager/UNIX_ObjectManager.h>
#include <ProtocolAdapter/UNIX_ProtocolAdapter.h>
#include <ObjectManagerAdapter/UNIX_ObjectManagerAdapter.h>
#include <FibreProtocolService/UNIX_FibreProtocolService.h>
#include <AccountManagementService/UNIX_AccountManagementService.h>
#include <VerificationService/UNIX_VerificationService.h>
#include <IdentityManagementService/UNIX_IdentityManagementService.h>
#include <StorageHardwareIDManagementService/UNIX_StorageHardwareIDManagementService.h>
#include <CertificateAuthority/UNIX_CertificateAuthority.h>
#include <SharedSecretService/UNIX_SharedSecretService.h>
#include <PublicKeyManagementService/UNIX_PublicKeyManagementService.h>
#include <KeyBasedCredentialManagementService/UNIX_KeyBasedCredentialManagementService.h>
#include <CertificateManagementService/UNIX_CertificateManagementService.h>
#include <Notary/UNIX_Notary.h>
#include <KerberosKeyDistributionCenter/UNIX_KerberosKeyDistributionCenter.h>
#include <AuthorizationService/UNIX_AuthorizationService.h>
#include <PrivilegeManagementService/UNIX_PrivilegeManagementService.h>
#include <RoleBasedAuthorizationService/UNIX_RoleBasedAuthorizationService.h>
#include <PlatformWatchdogService/UNIX_PlatformWatchdogService.h>
#include <ClusteringService/UNIX_ClusteringService.h>
#include <MetricService/UNIX_MetricService.h>
#include <StorageConfigurationService/UNIX_StorageConfigurationService.h>
#include <ConfigurationReportingService/UNIX_ConfigurationReportingService.h>
#include <IPConfigurationService/UNIX_IPConfigurationService.h>
#include <IndicationService/UNIX_IndicationService.h>
#include <SoftwareInstallationService/UNIX_SoftwareInstallationService.h>
#include <DiagnosticService/UNIX_DiagnosticService.h>
#include <DiagnosticTest/UNIX_DiagnosticTest.h>
#include <TimeService/UNIX_TimeService.h>
#include <PowerUtilizationManagementService/UNIX_PowerUtilizationManagementService.h>
#include <StatisticsService/UNIX_StatisticsService.h>
#include <BlockStatisticsService/UNIX_BlockStatisticsService.h>
#include <VLANService/UNIX_VLANService.h>
#include <Specific802dot1QVLANService/UNIX_Specific802dot1QVLANService.h>
#include <WakeUpService/UNIX_WakeUpService.h>
#include <OpaqueManagementDataService/UNIX_OpaqueManagementDataService.h>
#include <DatabaseService/UNIX_DatabaseService.h>
#include <BootService/UNIX_BootService.h>
#include <NetworkPortConfigurationService/UNIX_NetworkPortConfigurationService.h>
#include <WiFiPortConfigurationService/UNIX_WiFiPortConfigurationService.h>
#include <PrintMarker/UNIX_PrintMarker.h>
#include <PrintSupply/UNIX_PrintSupply.h>
#include <PrintInterpreter/UNIX_PrintInterpreter.h>
#include <PrintInputTray/UNIX_PrintInputTray.h>
#include <RoutingPolicy/UNIX_RoutingPolicy.h>
#include <X509CredentialFilterEntry/UNIX_X509CredentialFilterEntry.h>
#include <FilterEntry/UNIX_FilterEntry.h>
#include <PreambleFilter/UNIX_PreambleFilter.h>
#include <PeerIDPayloadFilterEntry/UNIX_PeerIDPayloadFilterEntry.h>
#include <Hdr8021Filter/UNIX_Hdr8021Filter.h>
#include <IPSOFilterEntry/UNIX_IPSOFilterEntry.h>
#include <IPHeadersFilter/UNIX_IPHeadersFilter.h>
#include <StaticForwardingEntry/UNIX_StaticForwardingEntry.h>
#include <SoftwareIdentity/UNIX_SoftwareIdentity.h>
#include <SoftwareElement/UNIX_SoftwareElement.h>
#include <VideoBIOSElement/UNIX_VideoBIOSElement.h>
#include <BIOSElement/UNIX_BIOSElement.h>
#include <ResourcePool/UNIX_ResourcePool.h>
#include <BGPIPRoute/UNIX_BGPIPRoute.h>
#include <AdministrativeDistance/UNIX_AdministrativeDistance.h>
#include <DynamicForwardingEntry/UNIX_DynamicForwardingEntry.h>
#include <SpareGroup/UNIX_SpareGroup.h>
#include <StorageRedundancyGroup/UNIX_StorageRedundancyGroup.h>
#include <ExtraCapacityGroup/UNIX_ExtraCapacityGroup.h>
#include <BGPAttributes/UNIX_BGPAttributes.h>
#include <FilterList/UNIX_FilterList.h>
#include <SoftwareFeature/UNIX_SoftwareFeature.h>
#include <BIOSFeature/UNIX_BIOSFeature.h>
#include <AGPSoftwareFeature/UNIX_AGPSoftwareFeature.h>
#include <VideoBIOSFeature/UNIX_VideoBIOSFeature.h>
#include <OSPFAreaConfiguration/UNIX_OSPFAreaConfiguration.h>
#include <OtherRoleInformation/UNIX_OtherRoleInformation.h>
#include <OtherPersonInformation/UNIX_OtherPersonInformation.h>
#include <Location/UNIX_Location.h>
#include <TraceLevelType/UNIX_TraceLevelType.h>
#include <AggregationMetricDefinition/UNIX_AggregationMetricDefinition.h>
#include <MetricDefinition/UNIX_MetricDefinition.h>
#include <ListenerDestinationWSManagement/UNIX_ListenerDestinationWSManagement.h>
#include <IndicationHandlerCIMXML/UNIX_IndicationHandlerCIMXML.h>
#include <ListenerDestinationCIMXML/UNIX_ListenerDestinationCIMXML.h>
#include <SystemIdentification/UNIX_SystemIdentification.h>
#include <BlockStatisticsManifest/UNIX_BlockStatisticsManifest.h>
#include <IKEProposal/UNIX_IKEProposal.h>
#include <IPsecProposal/UNIX_IPsecProposal.h>
#include <DatabaseParameter/UNIX_DatabaseParameter.h>
#include <DatabaseSegmentSettingData/UNIX_DatabaseSegmentSettingData.h>
#include <IPCOMPTransform/UNIX_IPCOMPTransform.h>
#include <ESPTransform/UNIX_ESPTransform.h>
#include <AHTransform/UNIX_AHTransform.h>
#include <FileSystemSettingData/UNIX_FileSystemSettingData.h>
#include <ExtendedStaticIPAssignmentSettingData/UNIX_ExtendedStaticIPAssignmentSettingData.h>
#include <DHCPSettingData/UNIX_DHCPSettingData.h>
#include <DNSGeneralSettingData/UNIX_DNSGeneralSettingData.h>
#include <DNSSettingData/UNIX_DNSSettingData.h>
#include <StaticIPAssignmentSettingData/UNIX_StaticIPAssignmentSettingData.h>
#include <iSCSISessionSettings/UNIX_iSCSISessionSettings.h>
#include <DiagnosticSettingData/UNIX_DiagnosticSettingData.h>
#include <StatisticalSetting/UNIX_StatisticalSetting.h>
#include <StorageSetting/UNIX_StorageSetting.h>
#include <StorageSettingWithHints/UNIX_StorageSettingWithHints.h>
#include <EthernetPortAllocationSettingData/UNIX_EthernetPortAllocationSettingData.h>
#include <ProcessorAllocationSettingData/UNIX_ProcessorAllocationSettingData.h>
#include <PowerAllocationSettingData/UNIX_PowerAllocationSettingData.h>
#include <StorageAllocationSettingData/UNIX_StorageAllocationSettingData.h>
#include <BootConfigSetting/UNIX_BootConfigSetting.h>
#include <SSHSettingData/UNIX_SSHSettingData.h>
#include <IndicationServiceSettingData/UNIX_IndicationServiceSettingData.h>
#include <VirtualSystemSettingData/UNIX_VirtualSystemSettingData.h>
#include <VirtualEthernetSwitchSettingData/UNIX_VirtualEthernetSwitchSettingData.h>
#include <IEEE8021xSettings/UNIX_IEEE8021xSettings.h>
#include <VLANEndpointSettingData/UNIX_VLANEndpointSettingData.h>
#include <LogicalPortSettings/UNIX_LogicalPortSettings.h>
#include <StorageClientSettingData/UNIX_StorageClientSettingData.h>
#include <VirtualSystemMigrationSettingData/UNIX_VirtualSystemMigrationSettingData.h>
#include <VideoHeadResolution/UNIX_VideoHeadResolution.h>
#include <BootSettingData/UNIX_BootSettingData.h>
#include <CLPSettingData/UNIX_CLPSettingData.h>
#include <WiFiNetworkDetectionSettings/UNIX_WiFiNetworkDetectionSettings.h>
#include <SCSIMultipathSettings/UNIX_SCSIMultipathSettings.h>
#include <CommonDatabaseSettingData/UNIX_CommonDatabaseSettingData.h>
#include <WiFiEndpointSettings/UNIX_WiFiEndpointSettings.h>
#include <iSCSIConnectionSettings/UNIX_iSCSIConnectionSettings.h>
#include <AccountSettingData/UNIX_AccountSettingData.h>
#include <ConnectivityMembershipSettingData/UNIX_ConnectivityMembershipSettingData.h>
#include <ZoneMembershipSettingData/UNIX_ZoneMembershipSettingData.h>
#include <BootSourceSetting/UNIX_BootSourceSetting.h>
#include <SAEndpointRefreshSettings/UNIX_SAEndpointRefreshSettings.h>
#include <IPVersionSettingData/UNIX_IPVersionSettingData.h>
#include <JobSettingData/UNIX_JobSettingData.h>
#include <FCSwitchSettings/UNIX_FCSwitchSettings.h>
#include <IndicationFilter/UNIX_IndicationFilter.h>
#include <OtherOrgUnitInformation/UNIX_OtherOrgUnitInformation.h>
#include <MethodParameters/UNIX_MethodParameters.h>
#include <ConfigurationCapacity/UNIX_ConfigurationCapacity.h>
#include <MemoryCapacity/UNIX_MemoryCapacity.h>
#include <KerberosCredential/UNIX_KerberosCredential.h>
#include <KerberosTicket/UNIX_KerberosTicket.h>
#include <NamedCredential/UNIX_NamedCredential.h>
#include <PublicKeyCertificate/UNIX_PublicKeyCertificate.h>
#include <X509CRL/UNIX_X509CRL.h>
#include <X509Certificate/UNIX_X509Certificate.h>
#include <NamedSharedIKESecret/UNIX_NamedSharedIKESecret.h>
#include <SharedSecret/UNIX_SharedSecret.h>
#include <UnsignedPublicKey/UNIX_UnsignedPublicKey.h>
#include <SharedCredential/UNIX_SharedCredential.h>
#include <UnsignedCredential/UNIX_UnsignedCredential.h>
#include <MediaAccessStatData/UNIX_MediaAccessStatData.h>
#include <PickerStatData/UNIX_PickerStatData.h>
#include <DatabaseServiceStatistics/UNIX_DatabaseServiceStatistics.h>
#include <FCPortStatistics/UNIX_FCPortStatistics.h>
#include <TokenRingPortStatistics/UNIX_TokenRingPortStatistics.h>
#include <EthernetPortStatistics/UNIX_EthernetPortStatistics.h>
#include <LLDPEthernetPortStatistics/UNIX_LLDPEthernetPortStatistics.h>
#include <BlockStorageStatisticalData/UNIX_BlockStorageStatisticalData.h>
#include <SAEndpointConnectionStatistics/UNIX_SAEndpointConnectionStatistics.h>
#include <iSCSILoginStatistics/UNIX_iSCSILoginStatistics.h>
#include <iSCSISessionFailures/UNIX_iSCSISessionFailures.h>
#include <FCPortRateStatistics/UNIX_FCPortRateStatistics.h>
#include <MediaPhysicalStatData/UNIX_MediaPhysicalStatData.h>
#include <DatabaseResourceStatistics/UNIX_DatabaseResourceStatistics.h>
#include <StatisticalRuntimeOverview/UNIX_StatisticalRuntimeOverview.h>
#include <DeviceErrorData/UNIX_DeviceErrorData.h>
#include <BGPEndpointStatistics/UNIX_BGPEndpointStatistics.h>
#include <CommonDatabaseStatistics/UNIX_CommonDatabaseStatistics.h>
#include <CIMOMStatisticalData/UNIX_CIMOMStatisticalData.h>
#include <LabelReaderStatData/UNIX_LabelReaderStatData.h>
#include <StorageHardwareID/UNIX_StorageHardwareID.h>
#include <GatewayPathID/UNIX_GatewayPathID.h>
#include <IPNetworkIdentity/UNIX_IPNetworkIdentity.h>
#include <CredentialStore/UNIX_CredentialStore.h>
#include <Keystore/UNIX_Keystore.h>
#include <RangeOfIPAddresses/UNIX_RangeOfIPAddresses.h>
#include <StatisticsCollection/UNIX_StatisticsCollection.h>
#include <BlockStatisticsManifestCollection/UNIX_BlockStatisticsManifestCollection.h>
#include <LogicalPortGroup/UNIX_LogicalPortGroup.h>
#include <PCIPortGroup/UNIX_PCIPortGroup.h>
#include <NamedAddressCollection/UNIX_NamedAddressCollection.h>
#include <ZoneSet/UNIX_ZoneSet.h>
#include <OSPFLink/UNIX_OSPFLink.h>
#include <IPXConnectivityNetwork/UNIX_IPXConnectivityNetwork.h>
#include <LANConnectivitySegment/UNIX_LANConnectivitySegment.h>
#include <IPConnectivitySubnet/UNIX_IPConnectivitySubnet.h>
#include <Zone/UNIX_Zone.h>
#include <NetworkVLAN/UNIX_NetworkVLAN.h>
#include <PolicyRoleCollection/UNIX_PolicyRoleCollection.h>
#include <RedundancySet/UNIX_RedundancySet.h>
#include <StorageRedundancySet/UNIX_StorageRedundancySet.h>
#include <SCSITargetPortGroup/UNIX_SCSITargetPortGroup.h>
#include <Profile/UNIX_Profile.h>
#include <Group/UNIX_Group.h>
#include <FilterCollection/UNIX_FilterCollection.h>
#include <ReplacementSet/UNIX_ReplacementSet.h>
#include <Role/UNIX_Role.h>
#include <InstalledProduct/UNIX_InstalledProduct.h>
#include <ConcreteCollection/UNIX_ConcreteCollection.h>
#include <BGPCluster/UNIX_BGPCluster.h>
#include <DiskGroup/UNIX_DiskGroup.h>
#include <LANSegment/UNIX_LANSegment.h>
#include <IPXNetwork/UNIX_IPXNetwork.h>
#include <IPSubnet/UNIX_IPSubnet.h>
#include <BufferPool/UNIX_BufferPool.h>
#include <BGPPeerGroup/UNIX_BGPPeerGroup.h>
#include <IPAddressRange/UNIX_IPAddressRange.h>
#include <BIOSString/UNIX_BIOSString.h>
#include <BIOSInteger/UNIX_BIOSInteger.h>
#include <BIOSPassword/UNIX_BIOSPassword.h>
#include <BIOSEnumeration/UNIX_BIOSEnumeration.h>
#include <MethodResult/UNIX_MethodResult.h>
#include <UsersAccess/UNIX_UsersAccess.h>
#include <UserContact/UNIX_UserContact.h>
#include <Person/UNIX_Person.h>
#include <Organization/UNIX_Organization.h>
#include <OrgUnit/UNIX_OrgUnit.h>
#include <SecuritySensitivity/UNIX_SecuritySensitivity.h>
#include <PhysicalStatisticalInformation/UNIX_PhysicalStatisticalInformation.h>
#include <MediaPhysicalStatInfo/UNIX_MediaPhysicalStatInfo.h>
#include <LabelReaderStatInfo/UNIX_LabelReaderStatInfo.h>
#include <FCAdapterEventCounters/UNIX_FCAdapterEventCounters.h>
#include <FibrePortEventCounters/UNIX_FibrePortEventCounters.h>
#include <PickerStatInfo/UNIX_PickerStatInfo.h>
#include <MediaAccessStatInfo/UNIX_MediaAccessStatInfo.h>
#include <SystemStatisticalInformation/UNIX_SystemStatisticalInformation.h>
#include <DeviceErrorCounts/UNIX_DeviceErrorCounts.h>
#include <SpanningTreeStatistics/UNIX_SpanningTreeStatistics.h>
#include <TransparentBridgingStatistics/UNIX_TransparentBridgingStatistics.h>
#include <BGPStatistics/UNIX_BGPStatistics.h>
#include <SwitchPortStatistics/UNIX_SwitchPortStatistics.h>
#include <SwitchPortTransparentBridgingStatistics/UNIX_SwitchPortTransparentBridgingStatistics.h>
#include <SwitchPortSourceRoutingStatistics/UNIX_SwitchPortSourceRoutingStatistics.h>
#include <SwitchPortSpanningTreeStatistics/UNIX_SwitchPortSpanningTreeStatistics.h>
#include <ProcessStatisticalInformation/UNIX_ProcessStatisticalInformation.h>
#include <DiagnosticServiceRecord/UNIX_DiagnosticServiceRecord.h>
#include <DiagnosticCompletionRecord/UNIX_DiagnosticCompletionRecord.h>
#include <DiagnosticSettingDataRecord/UNIX_DiagnosticSettingDataRecord.h>
#include <DiagnosticSettingRecord/UNIX_DiagnosticSettingRecord.h>
#include <LogRecord/UNIX_LogRecord.h>
#include <LogEntry/UNIX_LogEntry.h>
#include <PrioritySchedulingElement/UNIX_PrioritySchedulingElement.h>
#include <BoundedPrioritySchedulingElement/UNIX_BoundedPrioritySchedulingElement.h>
#include <AllocationSchedulingElement/UNIX_AllocationSchedulingElement.h>
#include <WRRSchedulingElement/UNIX_WRRSchedulingElement.h>
#include <Namespace/UNIX_Namespace.h>
#include <NextHopRoute/UNIX_NextHopRoute.h>
#include <NextHopIPRoute/UNIX_NextHopIPRoute.h>
#include <USBRedirectionCapabilities/UNIX_USBRedirectionCapabilities.h>
#include <MediaRedirectionCapabilities/UNIX_MediaRedirectionCapabilities.h>
#include <BootServiceCapabilities/UNIX_BootServiceCapabilities.h>
#include <OpaqueManagementDataCapabilities/UNIX_OpaqueManagementDataCapabilities.h>
#include <PlatformWatchdogServiceCapabilities/UNIX_PlatformWatchdogServiceCapabilities.h>
#include <AlarmDeviceCapabilities/UNIX_AlarmDeviceCapabilities.h>
#include <FCSwitchCapabilities/UNIX_FCSwitchCapabilities.h>
#include <IndicatorLEDCapabilities/UNIX_IndicatorLEDCapabilities.h>
#include <RecordLogCapabilities/UNIX_RecordLogCapabilities.h>
#include <MetricServiceCapabilities/UNIX_MetricServiceCapabilities.h>
#include <DHCPCapabilities/UNIX_DHCPCapabilities.h>
#include <OperatingSystemCapabilities/UNIX_OperatingSystemCapabilities.h>
#include <WiFiEndpointCapabilities/UNIX_WiFiEndpointCapabilities.h>
#include <NetworkPortCapabilities/UNIX_NetworkPortCapabilities.h>
#include <WiFiPortCapabilities/UNIX_WiFiPortCapabilities.h>
#include <FCPortCapabilities/UNIX_FCPortCapabilities.h>
#include <VirtualSystemManagementCapabilities/UNIX_VirtualSystemManagementCapabilities.h>
#include <ProcessorCapabilities/UNIX_ProcessorCapabilities.h>
#include <LaunchInContextCapabilities/UNIX_LaunchInContextCapabilities.h>
#include <AccountManagementCapabilities/UNIX_AccountManagementCapabilities.h>
#include <CLPCapabilities/UNIX_CLPCapabilities.h>
#include <SSHCapabilities/UNIX_SSHCapabilities.h>
#include <PowerUtilizationManagementCapabilities/UNIX_PowerUtilizationManagementCapabilities.h>
#include <CredentialManagementCapabilities/UNIX_CredentialManagementCapabilities.h>
#include <CertificateManagementCapabilities/UNIX_CertificateManagementCapabilities.h>
#include <VLANEndpointCapabilities/UNIX_VLANEndpointCapabilities.h>
#include <QueryCapabilities/UNIX_QueryCapabilities.h>
#include <StorageReplicationCapabilities/UNIX_StorageReplicationCapabilities.h>
#include <IEEE8021xCapabilities/UNIX_IEEE8021xCapabilities.h>
#include <CommonDatabaseCapabilities/UNIX_CommonDatabaseCapabilities.h>
#include <BIOSServiceCapabilities/UNIX_BIOSServiceCapabilities.h>
#include <StorageCapabilities/UNIX_StorageCapabilities.h>
#include <OSPFServiceCapabilities/UNIX_OSPFServiceCapabilities.h>
#include <ComputerSystemNodeCapabilities/UNIX_ComputerSystemNodeCapabilities.h>
#include <StatisticsCapabilities/UNIX_StatisticsCapabilities.h>
#include <BlockStatisticsCapabilities/UNIX_BlockStatisticsCapabilities.h>
#include <PhysicalAssetCapabilities/UNIX_PhysicalAssetCapabilities.h>
#include <DeviceSharingCapabilities/UNIX_DeviceSharingCapabilities.h>
#include <IndicationServiceCapabilities/UNIX_IndicationServiceCapabilities.h>
#include <AllocationCapabilities/UNIX_AllocationCapabilities.h>
#include <LocalizationCapabilities/UNIX_LocalizationCapabilities.h>
#include <SoftwareInstallationServiceCapabilities/UNIX_SoftwareInstallationServiceCapabilities.h>
#include <VirtualSystemSnapshotServiceCapabilities/UNIX_VirtualSystemSnapshotServiceCapabilities.h>
#include <SCSIMultipathConfigurationCapabilities/UNIX_SCSIMultipathConfigurationCapabilities.h>
#include <ZoneCapabilities/UNIX_ZoneCapabilities.h>
#include <iSCSICapabilities/UNIX_iSCSICapabilities.h>
#include <PowerManagementCapabilities/UNIX_PowerManagementCapabilities.h>
#include <DiagnosticServiceCapabilities/UNIX_DiagnosticServiceCapabilities.h>
#include <FileSystemCapabilities/UNIX_FileSystemCapabilities.h>
#include <VirtualSystemSnapshotCapabilities/UNIX_VirtualSystemSnapshotCapabilities.h>
#include <ResourcePoolConfigurationCapabilities/UNIX_ResourcePoolConfigurationCapabilities.h>
#include <PrivilegeManagementCapabilities/UNIX_PrivilegeManagementCapabilities.h>
#include <RoleBasedManagementCapabilities/UNIX_RoleBasedManagementCapabilities.h>
#include <StorageConfigurationCapabilities/UNIX_StorageConfigurationCapabilities.h>
#include <ProtocolControllerMaskingCapabilities/UNIX_ProtocolControllerMaskingCapabilities.h>
#include <Privilege/UNIX_Privilege.h>
#include <AuthorizedPrivilege/UNIX_AuthorizedPrivilege.h>

#include "UNIX_ConcreteComponentDeps.h"




class UNIX_ConcreteComponent :
	public CIM_Component
{
public:

	UNIX_ConcreteComponent();
	~UNIX_ConcreteComponent();

	virtual Boolean initialize();
	virtual Boolean load(int&);
	virtual Boolean finalize();
	virtual Boolean find(Array<CIMKeyBinding>&);
	virtual Boolean validateKey(CIMKeyBinding&) const;
	virtual void setScope(CIMName);

	virtual Boolean getGroupComponent(CIMProperty&) const;
	virtual CIMInstance getGroupComponent() const;
	virtual Boolean getPartComponent(CIMProperty&) const;
	virtual CIMInstance getPartComponent() const;

private:
	CIMName currentScope;

#	include "UNIX_ConcreteComponentPrivate.h"

};

#endif /* UNIX_CONCRETECOMPONENT */
