//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_ConcreteComponent" }, 
    Aggregation, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::Settings" ), 
    Description ( 
       "Note: The Configuration and SystemConfiguration classes are "
       "deprecated in lieu of using a ConcreteComponent relationship "
       "to indicate a hierarchy of Settings or SettingData instances. "
       "Therefore, the aggregation of SystemSettings into System "
       "Configurations is replaced by the ConcreteComponent "
       "relationship between instances of Settings and SettingData. \n"
       "Deprecated description: This relationship associates "
       "System-specific Configuration objects with System-specific "
       "Setting objects, similar to the SettingContext association." )]
class CIM_SystemSettingContext {

      [Deprecated { "CIM_ConcreteComponent.GroupComponent" }, 
       Key, Aggregate, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: The Configuration object that aggregates "
          "the Setting." )]
   CIM_SystemConfiguration REF Context;

      [Deprecated { "CIM_ConcreteComponent.PartComponent" }, 
       Key, Description ( 
          "Note: The use of this element is deprecated. Deprecated "
          "description: An aggregated Setting." )]
   CIM_SystemSetting REF Setting;


};



class UNIX_SystemSettingContext : CIM_SystemSettingContext
{

};

