//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Abstract, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_Dependency is a generic association used to establish "
       "dependency relationships between ManagedElements." )]
class CIM_Dependency {

      [Key, Description ( 
          "Antecedent represents the independent object in this association."
           )]
   CIM_ManagedElement REF Antecedent;

      [Key, Description ( 
          "Dependent represents the object that is dependent on the "
          "Antecedent." )]
   CIM_ManagedElement REF Dependent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.9.0" ), 
    UMLPackagePath ( "CIM::System::Logs" ), 
    Description ( 
       "ManagedSystemElements may record their event, error or "
       "informational data within Logs. The use of a Log to hold a "
       "ManagedSystemElement\'s data is described by this association. "
       "The type of Element data captured by the Log can be specified "
       "using the RecordedData string property." )]
class CIM_UseOfLog : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Log." )]
   CIM_Log REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The ManagedSystemElement whose information is recorded in the Log."
           )]
   CIM_ManagedSystemElement REF Dependent;

      [Description ( 
          "A free-form string describing the use of the Log by the "
          "ManagedSystemElement." )]
   string RecordedData;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.9.0" ), 
    UMLPackagePath ( "CIM::System::Logs" ), 
    Description ( 
       "ManagedSystemElements may record their event, error or "
       "informational data within MessageLogs. The use of a Log to "
       "hold a ManagedSystemElement\'s data is described by this "
       "association. \n"
       "UseOfMessageLog has the same semantics as UseOfLog. Users "
       "SHOULD reference UseOfLog in lieu of this association." )]
class CIM_UseOfMessageLog : CIM_UseOfLog {

      [Override ( "Antecedent" ), 
       Description ( "The MessageLog." )]
   CIM_MessageLog REF Antecedent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.8.0" ), 
    UMLPackagePath ( "CIM::System::Logs" ), 
    Description ( 
       "CIM_OperationLog is a specialization of the "
       "CIM_UseOfMessageLog association that identifies a reproducible "
       "record of operations for a LogicalElement." )]
class CIM_OperationLog : CIM_UseOfMessageLog {

      [Override ( "Antecedent" ), 
       Description ( 
          "The Log containing reproducible operations for the "
          "associated LogicalElement." )]
   CIM_MessageLog REF Antecedent;

      [Override ( "Dependent" ), 
       Min ( 1 ), 
       Max ( 1 ), 
       Description ( 
          "The LogicalElement for the associated OperationLog." )]
   CIM_LogicalElement REF Dependent;


};



class UNIX_OperationLog : CIM_OperationLog
{

};

