//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.6.0" ), 
    UMLPackagePath ( "CIM::Network::QoS" ), 
    Description ( 
       "The IETF\'s RFC2597 describes a Differentiated Services "
       "Per-Hop-Behavior (PHB) Group called Assured Forwarding (AF). "
       "Quoting from the RFC, \'The AF PHB group provides delivery of "
       "IP packets in four independently forwarded AF classes. Within "
       "each AF class, an IP packet can be assigned one of three "
       "different levels of drop precedence.\' The AFRelatedServices "
       "association describes the precedence of the individual AF "
       "drop-related Services within an AF IP packet-forwarding class." )]
class CIM_AFRelatedServices {

      [Key, Max ( 1 ), 
       Description ( 
          "The AFService with a lower drop precedence (ie, lower "
          "probability of dropping packets)." )]
   CIM_AFService REF AFLowerDropPrecedence;

      [Key, Description ( 
          "An AFService at the same IP packet-forwarding class "
          "level, but at a higher drop precedence." )]
   CIM_AFService REF AFHigherDropPrecedence;


};



class UNIX_AFRelatedServices : CIM_AFRelatedServices
{

};

