//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Abstract, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_Dependency is a generic association used to establish "
       "dependency relationships between ManagedElements." )]
class CIM_Dependency {

      [Key, Description ( 
          "Antecedent represents the independent object in this association."
           )]
   CIM_ManagedElement REF Antecedent;

      [Key, Description ( 
          "Dependent represents the object that is dependent on the "
          "Antecedent." )]
   CIM_ManagedElement REF Dependent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Network::OSPF" ), 
    Description ( 
       "This association connects address ranges to the OSPF area "
       "configuration. When network administrators want to control the "
       "advertisements of OSPF routers by filters, they first define "
       "the relevant ranges. In order for a router to handle a range, "
       "an instance of RangeOfIPAddresses MUST be associated to the "
       "router\'s OSPFAreaConfiguration, using this relationship. The "
       "association between the range and area configuration contains "
       "a property (EnableAdvertise) defining the handling - to allow "
       "or disallow advertismenets in the range." )]
class CIM_RangesOfConfiguration : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( 
          "The address range that is in the OSPF area configuration." )]
   CIM_RangeOfIPAddresses REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( 
          "The OSPF area configuration that contains the range." )]
   CIM_OSPFAreaConfiguration REF Dependent;

      [Description ( 
          "The address range is advertised (TRUE) or not (FALSE), "
          "see C.2 in RFC 2328." )]
   boolean EnableAdvertise;


};



class UNIX_RangesOfConfiguration : CIM_RangesOfConfiguration
{

};

