//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////

#pragma include ("Meta_Class20.mof")
#pragma include ("UNIX_OtherOrganizationInformation20.mof")
#pragma include ("UNIX_DirectorySpecification20.mof")
#pragma include ("UNIX_MemoryCheck20.mof")
#pragma include ("UNIX_VersionCompatibilityCheck20.mof")
#pragma include ("UNIX_DiskSpaceCheck20.mof")
#pragma include ("UNIX_SoftwareElementVersionCheck20.mof")
#pragma include ("UNIX_FileSpecification20.mof")
#pragma include ("UNIX_ArchitectureCheck20.mof")
#pragma include ("UNIX_OSVersionCheck20.mof")
#pragma include ("UNIX_SettingCheck20.mof")
#pragma include ("UNIX_SwapSpaceCheck20.mof")
#pragma include ("UNIX_RegisteredSubProfile20.mof")
#pragma include ("UNIX_RejectConnectionAction20.mof")
#pragma include ("UNIX_VendorPolicyAction20.mof")
#pragma include ("UNIX_NetworkPacketAction20.mof")
#pragma include ("UNIX_MethodAction20.mof")
#pragma include ("UNIX_CompoundPolicyAction20.mof")
#pragma include ("UNIX_IKEAction20.mof")
#pragma include ("UNIX_IPsecTunnelAction20.mof")
#pragma include ("UNIX_IPsecTransportAction20.mof")
#pragma include ("UNIX_PreconfiguredTunnelAction20.mof")
#pragma include ("UNIX_PreconfiguredTransportAction20.mof")
#pragma include ("UNIX_IPsecRule20.mof")
#pragma include ("UNIX_IKERule20.mof")
#pragma include ("UNIX_AuthenticationRule20.mof")
#pragma include ("UNIX_PolicyGroup20.mof")
#pragma include ("UNIX_VendorPolicyCondition20.mof")
#pragma include ("UNIX_DocumentAuthentication20.mof")
#pragma include ("UNIX_PublicPrivateKeyAuthentication20.mof")
#pragma include ("UNIX_KerberosAuthentication20.mof")
#pragma include ("UNIX_NetworkingIDAuthentication20.mof")
#pragma include ("UNIX_SharedSecretAuthentication20.mof")
#pragma include ("UNIX_PhysicalCredentialAuthentication20.mof")
#pragma include ("UNIX_AccountAuthentication20.mof")
#pragma include ("UNIX_BiometricAuthentication20.mof")
#pragma include ("UNIX_PolicyTimePeriodCondition20.mof")
#pragma include ("UNIX_QueryCondition20.mof")
#pragma include ("UNIX_PacketFilterCondition20.mof")
#pragma include ("UNIX_CompoundPolicyCondition20.mof")
#pragma include ("UNIX_StorageError20.mof")
#pragma include ("UNIX_MemoryError20.mof")
#pragma include ("UNIX_Configuration20.mof")
#pragma include ("UNIX_RebootAction20.mof")
#pragma include ("UNIX_ExecuteProgram20.mof")
#pragma include ("UNIX_CopyFileAction20.mof")
#pragma include ("UNIX_RemoveFileAction20.mof")
#pragma include ("UNIX_ModifySettingAction20.mof")
#pragma include ("UNIX_RemoveDirectoryAction20.mof")
#pragma include ("UNIX_CreateDirectoryAction20.mof")
#pragma include ("UNIX_FRU20.mof")
#pragma include ("UNIX_BaseMetricValue20.mof")
#pragma include ("UNIX_AggregationMetricValue20.mof")
#pragma include ("UNIX_View20.mof")
#pragma include ("UNIX_PhysicalComputerSystemView20.mof")
#pragma include ("UNIX_SupportAccess20.mof")
#pragma include ("UNIX_Product20.mof")
#pragma include ("UNIX_SystemConfiguration20.mof")
#pragma include ("UNIX_SystemSetting20.mof")
#pragma include ("UNIX_VideoControllerResolution20.mof")
#pragma include ("UNIX_DiagnosticSetting20.mof")
#pragma include ("UNIX_TimeZone20.mof")
#pragma include ("UNIX_MonitorResolution20.mof")
#pragma include ("UNIX_OtherGroupInformation20.mof")
#pragma include ("UNIX_PhysicalLink20.mof")
#pragma include ("UNIX_PhysicalMedia20.mof")
#pragma include ("UNIX_PhysicalTape20.mof")
#pragma include ("UNIX_Chip20.mof")
#pragma include ("UNIX_PhysicalMemory20.mof")
#pragma include ("UNIX_PhysicalConnector20.mof")
#pragma include ("UNIX_Slot20.mof")
#pragma include ("UNIX_Card20.mof")
#pragma include ("UNIX_SystemBusCard20.mof")
#pragma include ("UNIX_Rack20.mof")
#pragma include ("UNIX_Chassis20.mof")
#pragma include ("UNIX_PackageLocation20.mof")
#pragma include ("UNIX_StorageMediaLocation20.mof")
#pragma include ("UNIX_Magazine20.mof")
#pragma include ("UNIX_AuthenticationRequirement20.mof")
#pragma include ("UNIX_BGPRouteMap20.mof")
#pragma include ("UNIX_AccessControlInformation20.mof")
#pragma include ("UNIX_StoragePool20.mof")
#pragma include ("UNIX_ConcreteJob20.mof")
#pragma include ("UNIX_PrintJob20.mof")
#pragma include ("UNIX_DataFile20.mof")
#pragma include ("UNIX_FIFOPipeFile20.mof")
#pragma include ("UNIX_DeviceFile20.mof")
#pragma include ("UNIX_DeviceFile20.mof")
#pragma include ("UNIX_Directory20.mof")
#pragma include ("UNIX_Directory20.mof")
#pragma include ("UNIX_SymbolicLink20.mof")
#pragma include ("UNIX_BGPPathAttributes20.mof")
#pragma include ("UNIX_File20.mof")
#pragma include ("UNIX_FileSystem20.mof")
#pragma include ("UNIX_RemoteFileSystem20.mof")
#pragma include ("UNIX_NFS20.mof")
#pragma include ("UNIX_DatabaseStorageArea20.mof")
#pragma include ("UNIX_LocalFileSystem20.mof")
#pragma include ("UNIX_LocalFileSystem20.mof")
#pragma include ("UNIX_ApplicationSystem20.mof")
#pragma include ("UNIX_DatabaseSystem20.mof")
#pragma include ("UNIX_VirtualComputerSystem20.mof")
#pragma include ("UNIX_ComputerSystem20.mof")
#pragma include ("UNIX_Cluster20.mof")
#pragma include ("UNIX_StorageLibrary20.mof")
#pragma include ("UNIX_ReusablePolicyContainer20.mof")
#pragma include ("UNIX_RoutingProtocolDomain20.mof")
#pragma include ("UNIX_OSPFArea20.mof")
#pragma include ("UNIX_Network20.mof")
#pragma include ("UNIX_PolicyRepository20.mof")
#pragma include ("UNIX_AutonomousSystem20.mof")
#pragma include ("UNIX_DMA20.mof")
#pragma include ("UNIX_MemoryResource20.mof")
#pragma include ("UNIX_PortResource20.mof")
#pragma include ("UNIX_IRQ20.mof")
#pragma include ("UNIX_Process20.mof")
#pragma include ("UNIX_MessageLog20.mof")
#pragma include ("UNIX_DiagnosticLog20.mof")
#pragma include ("UNIX_DiagnosticsLog20.mof")
#pragma include ("UNIX_OperatingSystem20.mof")
#pragma include ("UNIX_Account20.mof")
#pragma include ("UNIX_JobQueue20.mof")
#pragma include ("UNIX_PrintQueue20.mof")
#pragma include ("UNIX_Thread20.mof")
#pragma include ("UNIX_CommonDatabase20.mof")
#pragma include ("UNIX_LogicalModule20.mof")
#pragma include ("UNIX_PassThroughModule20.mof")
#pragma include ("UNIX_LabelReader20.mof")
#pragma include ("UNIX_Scanner20.mof")
#pragma include ("UNIX_ProtocolController20.mof")
#pragma include ("UNIX_SCSIProtocolController20.mof")
#pragma include ("UNIX_WiFiRadio20.mof")
#pragma include ("UNIX_HeatPipe20.mof")
#pragma include ("UNIX_Refrigeration20.mof")
#pragma include ("UNIX_Fan20.mof")
#pragma include ("UNIX_PowerSource20.mof")
#pragma include ("UNIX_DesktopMonitor20.mof")
#pragma include ("UNIX_FlatPanel20.mof")
#pragma include ("UNIX_Keyboard20.mof")
#pragma include ("UNIX_PointingDevice20.mof")
#pragma include ("UNIX_CableModem20.mof")
#pragma include ("UNIX_SDSLModem20.mof")
#pragma include ("UNIX_HDSLModem20.mof")
#pragma include ("UNIX_VDSLModem20.mof")
#pragma include ("UNIX_ADSLModem20.mof")
#pragma include ("UNIX_POTSModem20.mof")
#pragma include ("UNIX_Unimodem20.mof")
#pragma include ("UNIX_ISDNModem20.mof")
#pragma include ("UNIX_FibrePort20.mof")
#pragma include ("UNIX_NetworkPort20.mof")
#pragma include ("UNIX_FCPort20.mof")
#pragma include ("UNIX_EthernetPort20.mof")
#pragma include ("UNIX_LLDPEthernetPort20.mof")
#pragma include ("UNIX_WiFiPort20.mof")
#pragma include ("UNIX_TokenRingPort20.mof")
#pragma include ("UNIX_PCIPort20.mof")
#pragma include ("UNIX_USBPort20.mof")
#pragma include ("UNIX_DisketteDrive20.mof")
#pragma include ("UNIX_MagnetoOpticalDrive20.mof")
#pragma include ("UNIX_DiskDrive20.mof")
#pragma include ("UNIX_CDROMDrive20.mof")
#pragma include ("UNIX_TapeDrive20.mof")
#pragma include ("UNIX_WORMDrive20.mof")
#pragma include ("UNIX_DVDDrive20.mof")
#pragma include ("UNIX_PowerSupply20.mof")
#pragma include ("UNIX_UninterruptiblePowerSupply20.mof")
#pragma include ("UNIX_DiscreteSensor20.mof")
#pragma include ("UNIX_MultiStateSensor20.mof")
#pragma include ("UNIX_TemperatureSensor20.mof")
#pragma include ("UNIX_VoltageSensor20.mof")
#pragma include ("UNIX_CurrentSensor20.mof")
#pragma include ("UNIX_Tachometer20.mof")
#pragma include ("UNIX_BinarySensor20.mof")
#pragma include ("UNIX_USBDevice20.mof")
#pragma include ("UNIX_USBHub20.mof")
#pragma include ("UNIX_LimitedAccessPort20.mof")
#pragma include ("UNIX_PickerElement20.mof")
#pragma include ("UNIX_InterLibraryPort20.mof")
#pragma include ("UNIX_ChangerDevice20.mof")
#pragma include ("UNIX_Door20.mof")
#pragma include ("UNIX_PCIBridge20.mof")
#pragma include ("UNIX_PCIeSwitch20.mof")
#pragma include ("UNIX_PCVideoController20.mof")
#pragma include ("UNIX_AGPVideoController20.mof")
#pragma include ("UNIX_ManagementController20.mof")
#pragma include ("UNIX_DisplayController20.mof")
#pragma include ("UNIX_PCMCIAController20.mof")
#pragma include ("UNIX_PortController20.mof")
#pragma include ("UNIX_SerialController20.mof")
#pragma include ("UNIX_ESCONController20.mof")
#pragma include ("UNIX_SSAController20.mof")
#pragma include ("UNIX_ParallelController20.mof")
#pragma include ("UNIX_SCSIController20.mof")
#pragma include ("UNIX_InfraredController20.mof")
#pragma include ("UNIX_USBController20.mof")
#pragma include ("UNIX_IDEController20.mof")
#pragma include ("UNIX_Battery20.mof")
#pragma include ("UNIX_Printer20.mof")
#pragma include ("UNIX_AlarmDevice20.mof")
#pragma include ("UNIX_StorageVolume20.mof")
#pragma include ("UNIX_VolumeSet20.mof")
#pragma include ("UNIX_LogicalDisk20.mof")
#pragma include ("UNIX_PhysicalExtent20.mof")
#pragma include ("UNIX_VolatileStorage20.mof")
#pragma include ("UNIX_NonVolatileStorage20.mof")
#pragma include ("UNIX_CacheMemory20.mof")
#pragma include ("UNIX_DatabaseSegment20.mof")
#pragma include ("UNIX_OpaqueManagementData20.mof")
#pragma include ("UNIX_AggregatePSExtent20.mof")
#pragma include ("UNIX_Snapshot20.mof")
#pragma include ("UNIX_AggregatePExtent20.mof")
#pragma include ("UNIX_TapePartition20.mof")
#pragma include ("UNIX_DiskPartition20.mof")
#pragma include ("UNIX_CompositeExtent20.mof")
#pragma include ("UNIX_ProtectedSpaceExtent20.mof")
#pragma include ("UNIX_Watchdog20.mof")
#pragma include ("UNIX_IndicatorLED20.mof")
#pragma include ("UNIX_Processor20.mof")
#pragma include ("UNIX_FibreChannelAdapter20.mof")
#pragma include ("UNIX_TokenRingAdapter20.mof")
#pragma include ("UNIX_EthernetAdapter20.mof")
#pragma include ("UNIX_VideoHead20.mof")
#pragma include ("UNIX_KVMRedirectionSAP20.mof")
#pragma include ("UNIX_CredentialManagementSAP20.mof")
#pragma include ("UNIX_IPNetworkConnection20.mof")
#pragma include ("UNIX_PrintSAP20.mof")
#pragma include ("UNIX_USBRedirectionSAP20.mof")
#pragma include ("UNIX_TextRedirectionSAP20.mof")
#pragma include ("UNIX_VLAN20.mof")
#pragma include ("UNIX_BootSAP20.mof")
#pragma include ("UNIX_ClusteringSAP20.mof")
#pragma include ("UNIX_ServiceAccessURI20.mof")
#pragma include ("UNIX_LaunchInContextSAP20.mof")
#pragma include ("UNIX_RemotePort20.mof")
#pragma include ("UNIX_MediaRedirectionSAP20.mof")
#pragma include ("UNIX_ObjectManagerCommunicationMechanism20.mof")
#pragma include ("UNIX_CIMXMLCommunicationMechanism20.mof")
#pragma include ("UNIX_VLANEndpoint20.mof")
#pragma include ("UNIX_SwitchPort20.mof")
#pragma include ("UNIX_IPXProtocolEndpoint20.mof")
#pragma include ("UNIX_CLPProtocolEndpoint20.mof")
#pragma include ("UNIX_SSHProtocolEndpoint20.mof")
#pragma include ("UNIX_BGPProtocolEndpoint20.mof")
#pragma include ("UNIX_DNSProtocolEndpoint20.mof")
#pragma include ("UNIX_IPProtocolEndpoint20.mof")
#pragma include ("UNIX_DHCPProtocolEndpoint20.mof")
#pragma include ("UNIX_LANEndpoint20.mof")
#pragma include ("UNIX_WiFiEndpoint20.mof")
#pragma include ("UNIX_IKESAEndpoint20.mof")
#pragma include ("UNIX_IPsecSAEndpoint20.mof")
#pragma include ("UNIX_SCSIProtocolEndpoint20.mof")
#pragma include ("UNIX_iSCSIProtocolEndpoint20.mof")
#pragma include ("UNIX_TCPProtocolEndpoint20.mof")
#pragma include ("UNIX_OSPFVirtualInterface20.mof")
#pragma include ("UNIX_OSPFProtocolEndpoint20.mof")
#pragma include ("UNIX_UDPProtocolEndpoint20.mof")
#pragma include ("UNIX_iSCSIConnection20.mof")
#pragma include ("UNIX_iSCSISession20.mof")
#pragma include ("UNIX_ProcessorCore20.mof")
#pragma include ("UNIX_HardwareThread20.mof")
#pragma include ("UNIX_ResourcePoolConfigurationService20.mof")
#pragma include ("UNIX_PrintService20.mof")
#pragma include ("UNIX_ControllerConfigurationService20.mof")
#pragma include ("UNIX_ZoneService20.mof")
#pragma include ("UNIX_ProtocolService20.mof")
#pragma include ("UNIX_VirtualSystemManagementService20.mof")
#pragma include ("UNIX_LaunchInContextService20.mof")
#pragma include ("UNIX_DropThresholdCalculationService20.mof")
#pragma include ("UNIX_IBSubnetManager20.mof")
#pragma include ("UNIX_REDDropperService20.mof")
#pragma include ("UNIX_WeightedREDDropperService20.mof")
#pragma include ("UNIX_HeadTailDropper20.mof")
#pragma include ("UNIX_QueuingService20.mof")
#pragma include ("UNIX_PacketSchedulingService20.mof")
#pragma include ("UNIX_NonWorkConservingSchedulingService20.mof")
#pragma include ("UNIX_ToSMarkerService20.mof")
#pragma include ("UNIX_Priority8021QMarkerService20.mof")
#pragma include ("UNIX_PreambleMarkerService20.mof")
#pragma include ("UNIX_DSCPMarkerService20.mof")
#pragma include ("UNIX_ClassifierService20.mof")
#pragma include ("UNIX_ClassifierElement20.mof")
#pragma include ("UNIX_TokenBucketMeterService20.mof")
#pragma include ("UNIX_EWMAMeterService20.mof")
#pragma include ("UNIX_AverageRateMeterService20.mof")
#pragma include ("UNIX_PowerManagementService20.mof")
#pragma include ("UNIX_BIOSService20.mof")
#pragma include ("UNIX_EFService20.mof")
#pragma include ("UNIX_AFService20.mof")
#pragma include ("UNIX_FlowService20.mof")
#pragma include ("UNIX_Hdr8021PService20.mof")
#pragma include ("UNIX_PrecedenceService20.mof")
#pragma include ("UNIX_HelpService20.mof")
#pragma include ("UNIX_SCSIPathConfigurationService20.mof")
#pragma include ("UNIX_SourceRoutingService20.mof")
#pragma include ("UNIX_SpanningTreeService20.mof")
#pragma include ("UNIX_TransparentBridgingService20.mof")
#pragma include ("UNIX_SwitchService20.mof")
#pragma include ("UNIX_BGPService20.mof")
#pragma include ("UNIX_OSPFService20.mof")
#pragma include ("UNIX_SharedDeviceManagementService20.mof")
#pragma include ("UNIX_VirtualSystemSnapshotService20.mof")
#pragma include ("UNIX_OOBAlertService20.mof")
#pragma include ("UNIX_USBRedirectionService20.mof")
#pragma include ("UNIX_TextRedirectionService20.mof")
#pragma include ("UNIX_ObjectManager20.mof")
#pragma include ("UNIX_ProtocolAdapter20.mof")
#pragma include ("UNIX_ObjectManagerAdapter20.mof")
#pragma include ("UNIX_FibreProtocolService20.mof")
#pragma include ("UNIX_AccountManagementService20.mof")
#pragma include ("UNIX_VerificationService20.mof")
#pragma include ("UNIX_IdentityManagementService20.mof")
#pragma include ("UNIX_StorageHardwareIDManagementService20.mof")
#pragma include ("UNIX_CertificateAuthority20.mof")
#pragma include ("UNIX_SharedSecretService20.mof")
#pragma include ("UNIX_PublicKeyManagementService20.mof")
#pragma include ("UNIX_KeyBasedCredentialManagementService20.mof")
#pragma include ("UNIX_CertificateManagementService20.mof")
#pragma include ("UNIX_Notary20.mof")
#pragma include ("UNIX_KerberosKeyDistributionCenter20.mof")
#pragma include ("UNIX_AuthorizationService20.mof")
#pragma include ("UNIX_PrivilegeManagementService20.mof")
#pragma include ("UNIX_RoleBasedAuthorizationService20.mof")
#pragma include ("UNIX_PlatformWatchdogService20.mof")
#pragma include ("UNIX_ClusteringService20.mof")
#pragma include ("UNIX_MetricService20.mof")
#pragma include ("UNIX_StorageConfigurationService20.mof")
#pragma include ("UNIX_ConfigurationReportingService20.mof")
#pragma include ("UNIX_IPConfigurationService20.mof")
#pragma include ("UNIX_IndicationService20.mof")
#pragma include ("UNIX_SoftwareInstallationService20.mof")
#pragma include ("UNIX_DiagnosticService20.mof")
#pragma include ("UNIX_DiagnosticTest20.mof")
#pragma include ("UNIX_TimeService20.mof")
#pragma include ("UNIX_PowerUtilizationManagementService20.mof")
#pragma include ("UNIX_StatisticsService20.mof")
#pragma include ("UNIX_BlockStatisticsService20.mof")
#pragma include ("UNIX_VLANService20.mof")
#pragma include ("UNIX_Specific802dot1QVLANService20.mof")
#pragma include ("UNIX_WakeUpService20.mof")
#pragma include ("UNIX_OpaqueManagementDataService20.mof")
#pragma include ("UNIX_DatabaseService20.mof")
#pragma include ("UNIX_BootService20.mof")
#pragma include ("UNIX_NetworkPortConfigurationService20.mof")
#pragma include ("UNIX_WiFiPortConfigurationService20.mof")
#pragma include ("UNIX_PrintMarker20.mof")
#pragma include ("UNIX_PrintSupply20.mof")
#pragma include ("UNIX_PrintInterpreter20.mof")
#pragma include ("UNIX_PrintInputTray20.mof")
#pragma include ("UNIX_RoutingPolicy20.mof")
#pragma include ("UNIX_X509CredentialFilterEntry20.mof")
#pragma include ("UNIX_FilterEntry20.mof")
#pragma include ("UNIX_PreambleFilter20.mof")
#pragma include ("UNIX_PeerIDPayloadFilterEntry20.mof")
#pragma include ("UNIX_Hdr8021Filter20.mof")
#pragma include ("UNIX_IPSOFilterEntry20.mof")
#pragma include ("UNIX_IPHeadersFilter20.mof")
#pragma include ("UNIX_StaticForwardingEntry20.mof")
#pragma include ("UNIX_SoftwareIdentity20.mof")
#pragma include ("UNIX_SoftwareElement20.mof")
#pragma include ("UNIX_VideoBIOSElement20.mof")
#pragma include ("UNIX_BIOSElement20.mof")
#pragma include ("UNIX_ResourcePool20.mof")
#pragma include ("UNIX_BGPIPRoute20.mof")
#pragma include ("UNIX_AdministrativeDistance20.mof")
#pragma include ("UNIX_DynamicForwardingEntry20.mof")
#pragma include ("UNIX_SpareGroup20.mof")
#pragma include ("UNIX_StorageRedundancyGroup20.mof")
#pragma include ("UNIX_ExtraCapacityGroup20.mof")
#pragma include ("UNIX_BGPAttributes20.mof")
#pragma include ("UNIX_FilterList20.mof")
#pragma include ("UNIX_SoftwareFeature20.mof")
#pragma include ("UNIX_BIOSFeature20.mof")
#pragma include ("UNIX_AGPSoftwareFeature20.mof")
#pragma include ("UNIX_VideoBIOSFeature20.mof")
#pragma include ("UNIX_OSPFAreaConfiguration20.mof")
#pragma include ("UNIX_OtherRoleInformation20.mof")
#pragma include ("UNIX_OtherPersonInformation20.mof")
#pragma include ("UNIX_Location20.mof")
#pragma include ("UNIX_TraceLevelType20.mof")
#pragma include ("UNIX_AggregationMetricDefinition20.mof")
#pragma include ("UNIX_MetricDefinition20.mof")
#pragma include ("UNIX_ListenerDestinationWSManagement20.mof")
#pragma include ("UNIX_IndicationHandlerCIMXML20.mof")
#pragma include ("UNIX_ListenerDestinationCIMXML20.mof")
#pragma include ("UNIX_SystemIdentification20.mof")
#pragma include ("UNIX_BlockStatisticsManifest20.mof")
#pragma include ("UNIX_IKEProposal20.mof")
#pragma include ("UNIX_IPsecProposal20.mof")
#pragma include ("UNIX_DatabaseParameter20.mof")
#pragma include ("UNIX_DatabaseSegmentSettingData20.mof")
#pragma include ("UNIX_IPCOMPTransform20.mof")
#pragma include ("UNIX_ESPTransform20.mof")
#pragma include ("UNIX_AHTransform20.mof")
#pragma include ("UNIX_FileSystemSettingData20.mof")
#pragma include ("UNIX_ExtendedStaticIPAssignmentSettingData20.mof")
#pragma include ("UNIX_DHCPSettingData20.mof")
#pragma include ("UNIX_DNSGeneralSettingData20.mof")
#pragma include ("UNIX_DNSSettingData20.mof")
#pragma include ("UNIX_StaticIPAssignmentSettingData20.mof")
#pragma include ("UNIX_iSCSISessionSettings20.mof")
#pragma include ("UNIX_DiagnosticSettingData20.mof")
#pragma include ("UNIX_StatisticalSetting20.mof")
#pragma include ("UNIX_StorageSetting20.mof")
#pragma include ("UNIX_StorageSettingWithHints20.mof")
#pragma include ("UNIX_EthernetPortAllocationSettingData20.mof")
#pragma include ("UNIX_ProcessorAllocationSettingData20.mof")
#pragma include ("UNIX_PowerAllocationSettingData20.mof")
#pragma include ("UNIX_StorageAllocationSettingData20.mof")
#pragma include ("UNIX_BootConfigSetting20.mof")
#pragma include ("UNIX_SSHSettingData20.mof")
#pragma include ("UNIX_IndicationServiceSettingData20.mof")
#pragma include ("UNIX_VirtualSystemSettingData20.mof")
#pragma include ("UNIX_VirtualEthernetSwitchSettingData20.mof")
#pragma include ("UNIX_IEEE8021xSettings20.mof")
#pragma include ("UNIX_VLANEndpointSettingData20.mof")
#pragma include ("UNIX_LogicalPortSettings20.mof")
#pragma include ("UNIX_StorageClientSettingData20.mof")
#pragma include ("UNIX_VirtualSystemMigrationSettingData20.mof")
#pragma include ("UNIX_VideoHeadResolution20.mof")
#pragma include ("UNIX_BootSettingData20.mof")
#pragma include ("UNIX_CLPSettingData20.mof")
#pragma include ("UNIX_WiFiNetworkDetectionSettings20.mof")
#pragma include ("UNIX_SCSIMultipathSettings20.mof")
#pragma include ("UNIX_CommonDatabaseSettingData20.mof")
#pragma include ("UNIX_WiFiEndpointSettings20.mof")
#pragma include ("UNIX_iSCSIConnectionSettings20.mof")
#pragma include ("UNIX_AccountSettingData20.mof")
#pragma include ("UNIX_ConnectivityMembershipSettingData20.mof")
#pragma include ("UNIX_ZoneMembershipSettingData20.mof")
#pragma include ("UNIX_BootSourceSetting20.mof")
#pragma include ("UNIX_SAEndpointRefreshSettings20.mof")
#pragma include ("UNIX_IPVersionSettingData20.mof")
#pragma include ("UNIX_JobSettingData20.mof")
#pragma include ("UNIX_FCSwitchSettings20.mof")
#pragma include ("UNIX_IndicationFilter20.mof")
#pragma include ("UNIX_OtherOrgUnitInformation20.mof")
#pragma include ("UNIX_MethodParameters20.mof")
#pragma include ("UNIX_ConfigurationCapacity20.mof")
#pragma include ("UNIX_MemoryCapacity20.mof")
#pragma include ("UNIX_KerberosCredential20.mof")
#pragma include ("UNIX_KerberosTicket20.mof")
#pragma include ("UNIX_NamedCredential20.mof")
#pragma include ("UNIX_PublicKeyCertificate20.mof")
#pragma include ("UNIX_X509CRL20.mof")
#pragma include ("UNIX_X509Certificate20.mof")
#pragma include ("UNIX_NamedSharedIKESecret20.mof")
#pragma include ("UNIX_SharedSecret20.mof")
#pragma include ("UNIX_UnsignedPublicKey20.mof")
#pragma include ("UNIX_SharedCredential20.mof")
#pragma include ("UNIX_UnsignedCredential20.mof")
#pragma include ("UNIX_MediaAccessStatData20.mof")
#pragma include ("UNIX_PickerStatData20.mof")
#pragma include ("UNIX_DatabaseServiceStatistics20.mof")
#pragma include ("UNIX_FCPortStatistics20.mof")
#pragma include ("UNIX_TokenRingPortStatistics20.mof")
#pragma include ("UNIX_EthernetPortStatistics20.mof")
#pragma include ("UNIX_LLDPEthernetPortStatistics20.mof")
#pragma include ("UNIX_BlockStorageStatisticalData20.mof")
#pragma include ("UNIX_SAEndpointConnectionStatistics20.mof")
#pragma include ("UNIX_iSCSILoginStatistics20.mof")
#pragma include ("UNIX_iSCSISessionFailures20.mof")
#pragma include ("UNIX_FCPortRateStatistics20.mof")
#pragma include ("UNIX_MediaPhysicalStatData20.mof")
#pragma include ("UNIX_DatabaseResourceStatistics20.mof")
#pragma include ("UNIX_StatisticalRuntimeOverview20.mof")
#pragma include ("UNIX_DeviceErrorData20.mof")
#pragma include ("UNIX_BGPEndpointStatistics20.mof")
#pragma include ("UNIX_CommonDatabaseStatistics20.mof")
#pragma include ("UNIX_CIMOMStatisticalData20.mof")
#pragma include ("UNIX_LabelReaderStatData20.mof")
#pragma include ("UNIX_StorageHardwareID20.mof")
#pragma include ("UNIX_GatewayPathID20.mof")
#pragma include ("UNIX_IPNetworkIdentity20.mof")
#pragma include ("UNIX_CredentialStore20.mof")
#pragma include ("UNIX_Keystore20.mof")
#pragma include ("UNIX_RangeOfIPAddresses20.mof")
#pragma include ("UNIX_StatisticsCollection20.mof")
#pragma include ("UNIX_BlockStatisticsManifestCollection20.mof")
#pragma include ("UNIX_LogicalPortGroup20.mof")
#pragma include ("UNIX_PCIPortGroup20.mof")
#pragma include ("UNIX_NamedAddressCollection20.mof")
#pragma include ("UNIX_ZoneSet20.mof")
#pragma include ("UNIX_OSPFLink20.mof")
#pragma include ("UNIX_IPXConnectivityNetwork20.mof")
#pragma include ("UNIX_LANConnectivitySegment20.mof")
#pragma include ("UNIX_IPConnectivitySubnet20.mof")
#pragma include ("UNIX_Zone20.mof")
#pragma include ("UNIX_NetworkVLAN20.mof")
#pragma include ("UNIX_PolicyRoleCollection20.mof")
#pragma include ("UNIX_RedundancySet20.mof")
#pragma include ("UNIX_StorageRedundancySet20.mof")
#pragma include ("UNIX_SCSITargetPortGroup20.mof")
#pragma include ("UNIX_Profile20.mof")
#pragma include ("UNIX_Group20.mof")
#pragma include ("UNIX_FilterCollection20.mof")
#pragma include ("UNIX_ReplacementSet20.mof")
#pragma include ("UNIX_Role20.mof")
#pragma include ("UNIX_InstalledProduct20.mof")
#pragma include ("UNIX_ConcreteCollection20.mof")
#pragma include ("UNIX_BGPCluster20.mof")
#pragma include ("UNIX_DiskGroup20.mof")
#pragma include ("UNIX_LANSegment20.mof")
#pragma include ("UNIX_IPXNetwork20.mof")
#pragma include ("UNIX_IPSubnet20.mof")
#pragma include ("UNIX_BufferPool20.mof")
#pragma include ("UNIX_BGPPeerGroup20.mof")
#pragma include ("UNIX_IPAddressRange20.mof")
#pragma include ("UNIX_BIOSString20.mof")
#pragma include ("UNIX_BIOSInteger20.mof")
#pragma include ("UNIX_BIOSPassword20.mof")
#pragma include ("UNIX_BIOSEnumeration20.mof")
#pragma include ("UNIX_MethodResult20.mof")
#pragma include ("UNIX_UsersAccess20.mof")
#pragma include ("UNIX_UserContact20.mof")
#pragma include ("UNIX_Person20.mof")
#pragma include ("UNIX_Organization20.mof")
#pragma include ("UNIX_OrgUnit20.mof")
#pragma include ("UNIX_SecuritySensitivity20.mof")
#pragma include ("UNIX_PhysicalStatisticalInformation20.mof")
#pragma include ("UNIX_MediaPhysicalStatInfo20.mof")
#pragma include ("UNIX_LabelReaderStatInfo20.mof")
#pragma include ("UNIX_FCAdapterEventCounters20.mof")
#pragma include ("UNIX_FibrePortEventCounters20.mof")
#pragma include ("UNIX_PickerStatInfo20.mof")
#pragma include ("UNIX_MediaAccessStatInfo20.mof")
#pragma include ("UNIX_SystemStatisticalInformation20.mof")
#pragma include ("UNIX_DeviceErrorCounts20.mof")
#pragma include ("UNIX_SpanningTreeStatistics20.mof")
#pragma include ("UNIX_TransparentBridgingStatistics20.mof")
#pragma include ("UNIX_BGPStatistics20.mof")
#pragma include ("UNIX_SwitchPortStatistics20.mof")
#pragma include ("UNIX_SwitchPortTransparentBridgingStatistics20.mof")
#pragma include ("UNIX_SwitchPortSourceRoutingStatistics20.mof")
#pragma include ("UNIX_SwitchPortSpanningTreeStatistics20.mof")
#pragma include ("UNIX_ProcessStatisticalInformation20.mof")
#pragma include ("UNIX_DiagnosticServiceRecord20.mof")
#pragma include ("UNIX_DiagnosticCompletionRecord20.mof")
#pragma include ("UNIX_DiagnosticSettingDataRecord20.mof")
#pragma include ("UNIX_DiagnosticSettingRecord20.mof")
#pragma include ("UNIX_LogRecord20.mof")
#pragma include ("UNIX_LogEntry20.mof")
#pragma include ("UNIX_PrioritySchedulingElement20.mof")
#pragma include ("UNIX_BoundedPrioritySchedulingElement20.mof")
#pragma include ("UNIX_AllocationSchedulingElement20.mof")
#pragma include ("UNIX_WRRSchedulingElement20.mof")
#pragma include ("UNIX_Namespace20.mof")
#pragma include ("UNIX_NextHopRoute20.mof")
#pragma include ("UNIX_NextHopIPRoute20.mof")
#pragma include ("UNIX_USBRedirectionCapabilities20.mof")
#pragma include ("UNIX_MediaRedirectionCapabilities20.mof")
#pragma include ("UNIX_BootServiceCapabilities20.mof")
#pragma include ("UNIX_OpaqueManagementDataCapabilities20.mof")
#pragma include ("UNIX_PlatformWatchdogServiceCapabilities20.mof")
#pragma include ("UNIX_AlarmDeviceCapabilities20.mof")
#pragma include ("UNIX_FCSwitchCapabilities20.mof")
#pragma include ("UNIX_IndicatorLEDCapabilities20.mof")
#pragma include ("UNIX_RecordLogCapabilities20.mof")
#pragma include ("UNIX_MetricServiceCapabilities20.mof")
#pragma include ("UNIX_DHCPCapabilities20.mof")
#pragma include ("UNIX_OperatingSystemCapabilities20.mof")
#pragma include ("UNIX_WiFiEndpointCapabilities20.mof")
#pragma include ("UNIX_NetworkPortCapabilities20.mof")
#pragma include ("UNIX_WiFiPortCapabilities20.mof")
#pragma include ("UNIX_FCPortCapabilities20.mof")
#pragma include ("UNIX_VirtualSystemManagementCapabilities20.mof")
#pragma include ("UNIX_ProcessorCapabilities20.mof")
#pragma include ("UNIX_LaunchInContextCapabilities20.mof")
#pragma include ("UNIX_AccountManagementCapabilities20.mof")
#pragma include ("UNIX_CLPCapabilities20.mof")
#pragma include ("UNIX_SSHCapabilities20.mof")
#pragma include ("UNIX_PowerUtilizationManagementCapabilities20.mof")
#pragma include ("UNIX_CredentialManagementCapabilities20.mof")
#pragma include ("UNIX_CertificateManagementCapabilities20.mof")
#pragma include ("UNIX_VLANEndpointCapabilities20.mof")
#pragma include ("UNIX_QueryCapabilities20.mof")
#pragma include ("UNIX_StorageReplicationCapabilities20.mof")
#pragma include ("UNIX_IEEE8021xCapabilities20.mof")
#pragma include ("UNIX_CommonDatabaseCapabilities20.mof")
#pragma include ("UNIX_BIOSServiceCapabilities20.mof")
#pragma include ("UNIX_StorageCapabilities20.mof")
#pragma include ("UNIX_OSPFServiceCapabilities20.mof")
#pragma include ("UNIX_ComputerSystemNodeCapabilities20.mof")
#pragma include ("UNIX_StatisticsCapabilities20.mof")
#pragma include ("UNIX_BlockStatisticsCapabilities20.mof")
#pragma include ("UNIX_PhysicalAssetCapabilities20.mof")
#pragma include ("UNIX_DeviceSharingCapabilities20.mof")
#pragma include ("UNIX_IndicationServiceCapabilities20.mof")
#pragma include ("UNIX_AllocationCapabilities20.mof")
#pragma include ("UNIX_LocalizationCapabilities20.mof")
#pragma include ("UNIX_SoftwareInstallationServiceCapabilities20.mof")
#pragma include ("UNIX_VirtualSystemSnapshotServiceCapabilities20.mof")
#pragma include ("UNIX_SCSIMultipathConfigurationCapabilities20.mof")
#pragma include ("UNIX_ZoneCapabilities20.mof")
#pragma include ("UNIX_iSCSICapabilities20.mof")
#pragma include ("UNIX_PowerManagementCapabilities20.mof")
#pragma include ("UNIX_DiagnosticServiceCapabilities20.mof")
#pragma include ("UNIX_FileSystemCapabilities20.mof")
#pragma include ("UNIX_VirtualSystemSnapshotCapabilities20.mof")
#pragma include ("UNIX_ResourcePoolConfigurationCapabilities20.mof")
#pragma include ("UNIX_PrivilegeManagementCapabilities20.mof")
#pragma include ("UNIX_RoleBasedManagementCapabilities20.mof")
#pragma include ("UNIX_StorageConfigurationCapabilities20.mof")
#pragma include ("UNIX_ProtocolControllerMaskingCapabilities20.mof")
#pragma include ("UNIX_Privilege20.mof")
#pragma include ("UNIX_AuthorizedPrivilege20.mof")
#pragma include ("UNIX_InstRead20.mof")
#pragma include ("UNIX_InstModification20.mof")
#pragma include ("UNIX_InstDeletion20.mof")
#pragma include ("UNIX_InstMethodCall20.mof")
#pragma include ("UNIX_InstCreation20.mof")
#pragma include ("UNIX_ClassCreation20.mof")
#pragma include ("UNIX_ClassDeletion20.mof")
#pragma include ("UNIX_ClassModification20.mof")
#pragma include ("UNIX_AlertInstIndication20.mof")
#pragma include ("UNIX_ThresholdIndication20.mof")
#pragma include ("UNIX_ContainedProposal20.mof")
#pragma include ("UNIX_ContainedTransform20.mof")
#pragma include ("UNIX_SettingsDefineCapabilities20.mof")
#pragma include ("UNIX_ProductSoftwareComponent20.mof")
#pragma include ("UNIX_QoSConditioningSubService20.mof")
#pragma include ("UNIX_SwitchServiceSpanningTree20.mof")
#pragma include ("UNIX_QoSSubService20.mof")
#pragma include ("UNIX_ClassifierElementInClassifierService20.mof")
#pragma include ("UNIX_SwitchServiceVLAN20.mof")
#pragma include ("UNIX_SwitchServiceSourceRouting20.mof")
#pragma include ("UNIX_SwitchServiceTransparentBridging20.mof")
#pragma include ("UNIX_AccountOnSystem20.mof")
#pragma include ("UNIX_HostedResourcePool20.mof")
#pragma include ("UNIX_ContainedDomain20.mof")
#pragma include ("UNIX_RoutingProtocolDomainInAS20.mof")
#pragma include ("UNIX_InstalledOS20.mof")
#pragma include ("UNIX_HostedFileSystem20.mof")
#pragma include ("UNIX_ASBGPEndpoints20.mof")
#pragma include ("UNIX_RoutersInAS20.mof")
#pragma include ("UNIX_ComponentCS20.mof")
#pragma include ("UNIX_SystemPartition20.mof")
#pragma include ("UNIX_HostedStoragePool20.mof")
#pragma include ("UNIX_FilterListInSystem20.mof")
#pragma include ("UNIX_ComputerSystemMemory20.mof")
#pragma include ("UNIX_ComputerSystemProcessor20.mof")
#pragma include ("UNIX_PolicyRepositoryInPolicyRepository20.mof")
#pragma include ("UNIX_SystemBIOS20.mof")
#pragma include ("UNIX_ApplicationSystemSoftwareFeature20.mof")
#pragma include ("UNIX_ComputerSystemIRQ20.mof")
#pragma include ("UNIX_ComputerSystemMappedIO20.mof")
#pragma include ("UNIX_ComputerSystemDMA20.mof")
#pragma include ("UNIX_FilterEntryInSystem20.mof")
#pragma include ("UNIX_Confederation20.mof")
#pragma include ("UNIX_PolicyContainerInPolicyContainer20.mof")
#pragma include ("UNIX_EndpointInArea20.mof")
#pragma include ("UNIX_OSProcess20.mof")
#pragma include ("UNIX_ListsInRoutingPolicy20.mof")
#pragma include ("UNIX_ConcreteComponent20.mof")
#pragma include ("UNIX_ModulePort20.mof")
#pragma include ("UNIX_DirectoryContainsFile20.mof")
#pragma include ("UNIX_OrderedComponent20.mof")
#pragma include ("UNIX_EntriesInFilterList20.mof")
#pragma include ("UNIX_OperatingSystemSoftwareFeature20.mof")
#pragma include ("UNIX_BGPServiceAttributes20.mof")
#pragma include ("UNIX_NetworkAdapterRedundancyComponent20.mof")
#pragma include ("UNIX_PExtentRedundancyComponent20.mof")
#pragma include ("UNIX_AggregateRedundancyComponent20.mof")
#pragma include ("UNIX_ProcessOfJob20.mof")
#pragma include ("UNIX_ContainedLocation20.mof")
#pragma include ("UNIX_PolicyGroupInPolicyGroup20.mof")
#pragma include ("UNIX_PolicyConditionInPolicyRule20.mof")
#pragma include ("UNIX_PacketConditionInSARule20.mof")
#pragma include ("UNIX_PolicyConditionInPolicyCondition20.mof")
#pragma include ("UNIX_PolicyActionInPolicyRule20.mof")
#pragma include ("UNIX_PolicyActionInPolicyAction20.mof")
#pragma include ("UNIX_PolicySetComponent20.mof")
#pragma include ("UNIX_PolicyRuleValidityPeriod20.mof")
#pragma include ("UNIX_PolicyRuleInPolicyGroup20.mof")
#pragma include ("UNIX_PolicySetValidityPeriod20.mof")
#pragma include ("UNIX_AssociatedRemainingExtent20.mof")
#pragma include ("UNIX_FilteredBGPAttributes20.mof")
#pragma include ("UNIX_SoftwareElementComponent20.mof")
#pragma include ("UNIX_PrintJobFile20.mof")
#pragma include ("UNIX_BIOSFeatureBIOSElements20.mof")
#pragma include ("UNIX_VideoBIOSFeatureVideoBIOSElements20.mof")
#pragma include ("UNIX_ProductPhysicalComponent20.mof")
#pragma include ("UNIX_AssociatedComponentExtent20.mof")
#pragma include ("UNIX_VirtualSystemSettingDataComponent20.mof")
#pragma include ("UNIX_DatabaseFile20.mof")
#pragma include ("UNIX_ProductComponent20.mof")
#pragma include ("UNIX_CollectionOfSensors20.mof")
#pragma include ("UNIX_DiagnosticTestInPackage20.mof")
#pragma include ("UNIX_ApplicationSystemHierarchy20.mof")
#pragma include ("UNIX_FileStorage20.mof")
#pragma include ("UNIX_LinkHasConnector20.mof")
#pragma include ("UNIX_ConnectorOnPackage20.mof")
#pragma include ("UNIX_PackagedComponent20.mof")
#pragma include ("UNIX_MemoryOnCard20.mof")
#pragma include ("UNIX_CardOnCard20.mof")
#pragma include ("UNIX_ChassisInRack20.mof")
#pragma include ("UNIX_PackageInChassis20.mof")
#pragma include ("UNIX_NetworkPipeComposition20.mof")
#pragma include ("UNIX_ProductServiceComponent20.mof")
#pragma include ("UNIX_SoftwareFeatureComponent20.mof")
#pragma include ("UNIX_ProductElementComponent20.mof")
#pragma include ("UNIX_DatabaseStorage20.mof")
#pragma include ("UNIX_ProcessThread20.mof")
#pragma include ("UNIX_BGPRouteMapsInRoutingPolicy20.mof")
#pragma include ("UNIX_ElementInSchedulingService20.mof")
#pragma include ("UNIX_ConcreteIdentity20.mof")
#pragma include ("UNIX_FileIdentity20.mof")
#pragma include ("UNIX_NetworkVirtualAdapter20.mof")
#pragma include ("UNIX_DeviceIdentity20.mof")
#pragma include ("UNIX_AccountIdentity20.mof")
#pragma include ("UNIX_EndpointIdentity20.mof")
#pragma include ("UNIX_ElementSettingData20.mof")
#pragma include ("UNIX_TransformOfSecurityAssociation20.mof")
#pragma include ("UNIX_ErrorCountersForDevice20.mof")
#pragma include ("UNIX_SystemStatistics20.mof")
#pragma include ("UNIX_ServiceStatistics20.mof")
#pragma include ("UNIX_BGPServiceStatistics20.mof")
#pragma include ("UNIX_DeviceStatistics20.mof")
#pragma include ("UNIX_ProcessStatistics20.mof")
#pragma include ("UNIX_SAPStatistics20.mof")
#pragma include ("UNIX_PhysicalStatistics20.mof")
#pragma include ("UNIX_EndpointInLink20.mof")
#pragma include ("UNIX_MemberPrincipal20.mof")
#pragma include ("UNIX_ElementInPolicyRoleCollection20.mof")
#pragma include ("UNIX_BGPPeerUsesRouteMap20.mof")
#pragma include ("UNIX_RoutersInBGPCluster20.mof")
#pragma include ("UNIX_DriveInDiskGroup20.mof")
#pragma include ("UNIX_InLogicalNetwork20.mof")
#pragma include ("UNIX_InSegment20.mof")
#pragma include ("UNIX_InBGPPeerGroup20.mof")
#pragma include ("UNIX_ExtentInDiskGroup20.mof")
#pragma include ("UNIX_OrderedMemberOfCollection20.mof")
#pragma include ("UNIX_CollectedSoftwareFeatures20.mof")
#pragma include ("UNIX_CollectedSoftwareElements20.mof")
#pragma include ("UNIX_PolicySetInRoleCollection20.mof")
#pragma include ("UNIX_CollectedBufferPool20.mof")
#pragma include ("UNIX_ClassifierElementUsesFilterList20.mof")
#pragma include ("UNIX_BIOSLoadedInNV20.mof")
#pragma include ("UNIX_LogInStorage20.mof")
#pragma include ("UNIX_UseOfLog20.mof")
#pragma include ("UNIX_UseOfMessageLog20.mof")
#pragma include ("UNIX_OperationLog20.mof")
#pragma include ("UNIX_FilterOfSecurityAssociation20.mof")
#pragma include ("UNIX_ElementAsUser20.mof")
#pragma include ("UNIX_MemoryWithMedia20.mof")
#pragma include ("UNIX_WakeUpServiceOnNetworkPort20.mof")
#pragma include ("UNIX_WakeUpServiceOnNetworkAdapter20.mof")
#pragma include ("UNIX_WakeUpServiceOnModem20.mof")
#pragma include ("UNIX_OOBAlertServiceOnNetworkPort20.mof")
#pragma include ("UNIX_OOBAlertServiceOnModem20.mof")
#pragma include ("UNIX_OOBAlertServiceOnNetworkAdapter20.mof")
#pragma include ("UNIX_AuthorizationSubject20.mof")
#pragma include ("UNIX_Docked20.mof")
#pragma include ("UNIX_SoftwareFeatureSAPImplementation20.mof")
#pragma include ("UNIX_TransparentBridgingStaticForwarding20.mof")
#pragma include ("UNIX_ResidesOnExtent20.mof")
#pragma include ("UNIX_RemoteAccessAvailableToElement20.mof")
#pragma include ("UNIX_PeerGatewayForPreconfiguredTunnel20.mof")
#pragma include ("UNIX_AccessLabelReader20.mof")
#pragma include ("UNIX_PickerLabelReader20.mof")
#pragma include ("UNIX_ManagesAccount20.mof")
#pragma include ("UNIX_BootOSFromFS20.mof")
#pragma include ("UNIX_ApplicationSystemDependency20.mof")
#pragma include ("UNIX_ElementView20.mof")
#pragma include ("UNIX_RoutesBGP20.mof")
#pragma include ("UNIX_SecurityServiceUsesAccount20.mof")
#pragma include ("UNIX_LastAppliedSnapshot20.mof")
#pragma include ("UNIX_AllocatedFromStoragePool20.mof")
#pragma include ("UNIX_AssociatedBattery20.mof")
#pragma include ("UNIX_RunningOS20.mof")
#pragma include ("UNIX_ReferencedProfile20.mof")
#pragma include ("UNIX_SubProfileRequiresProfile20.mof")
#pragma include ("UNIX_ClassifierFilterSet20.mof")
#pragma include ("UNIX_RequireCredentialsFrom20.mof")
#pragma include ("UNIX_PickerForChanger20.mof")
#pragma include ("UNIX_QueueHierarchy20.mof")
#pragma include ("UNIX_EGPRouteCalcDependency20.mof")
#pragma include ("UNIX_SchedulerUsed20.mof")
#pragma include ("UNIX_RelatedSpanningTree20.mof")
#pragma include ("UNIX_CalculationBasedOnQueue20.mof")
#pragma include ("UNIX_ServiceUsesSecurityService20.mof")
#pragma include ("UNIX_CalculationServiceForDropper20.mof")
#pragma include ("UNIX_SecurityServiceForSystem20.mof")
#pragma include ("UNIX_ManagesAccountOnSystem20.mof")
#pragma include ("UNIX_DiagnosticTestForMSE20.mof")
#pragma include ("UNIX_MoreGroupInfo20.mof")
#pragma include ("UNIX_Spared20.mof")
#pragma include ("UNIX_QueueAllocation20.mof")
#pragma include ("UNIX_AssociatedProcessorMemory20.mof")
#pragma include ("UNIX_AssociatedCacheMemory20.mof")
#pragma include ("UNIX_SystemAdministratorRole20.mof")
#pragma include ("UNIX_ElementInConnector20.mof")
#pragma include ("UNIX_PackageInConnector20.mof")
#pragma include ("UNIX_PackageInSlot20.mof")
#pragma include ("UNIX_CardInSlot20.mof")
#pragma include ("UNIX_AcceptCredentialFrom20.mof")
#pragma include ("UNIX_CommMechanismForObjectManagerAdapter20.mof")
#pragma include ("UNIX_ElementSoftwareIdentity20.mof")
#pragma include ("UNIX_MoreOrgUnitInfo20.mof")
#pragma include ("UNIX_HostedNetworkPipe20.mof")
#pragma include ("UNIX_HostedFilterList20.mof")
#pragma include ("UNIX_HostedACI20.mof")
#pragma include ("UNIX_HostedRoutingServices20.mof")
#pragma include ("UNIX_HostedClusterService20.mof")
#pragma include ("UNIX_HostedForwardingServices20.mof")
#pragma include ("UNIX_HostedBootService20.mof")
#pragma include ("UNIX_SharingDependency20.mof")
#pragma include ("UNIX_HostedJobDestination20.mof")
#pragma include ("UNIX_HostedBGPPeerGroup20.mof")
#pragma include ("UNIX_NetworkServicesInAdminDomain20.mof")
#pragma include ("UNIX_HostedBGPRouteMap20.mof")
#pragma include ("UNIX_ScopedSetting20.mof")
#pragma include ("UNIX_HostedClusterSAP20.mof")
#pragma include ("UNIX_HostedBootSAP20.mof")
#pragma include ("UNIX_HostedBGPAttributes20.mof")
#pragma include ("UNIX_HostedAuthenticationRequirement20.mof")
#pragma include ("UNIX_SettingForSystem20.mof")
#pragma include ("UNIX_HostedFilterEntryBase20.mof")
#pragma include ("UNIX_ConfigurationForSystem20.mof")
#pragma include ("UNIX_PolicyRuleInSystem20.mof")
#pragma include ("UNIX_PolicyGroupInSystem20.mof")
#pragma include ("UNIX_PolicyActionInPolicyRepository20.mof")
#pragma include ("UNIX_ReusablePolicy20.mof")
#pragma include ("UNIX_PolicyConditionInPolicyRepository20.mof")
#pragma include ("UNIX_HostedRoute20.mof")
#pragma include ("UNIX_HostedCollection20.mof")
#pragma include ("UNIX_PolicyRoleCollectionInSystem20.mof")
#pragma include ("UNIX_NamespaceInManager20.mof")
#pragma include ("UNIX_DatabaseControlFile20.mof")
#pragma include ("UNIX_HostedAdminDistance20.mof")
#pragma include ("UNIX_HostedRoutingPolicy20.mof")
#pragma include ("UNIX_HostingCS20.mof")
#pragma include ("UNIX_FibrePortOnFCAdapter20.mof")
#pragma include ("UNIX_USBPortOnHub20.mof")
#pragma include ("UNIX_PhysicalMediaInLocation20.mof")
#pragma include ("UNIX_QueueForPrintService20.mof")
#pragma include ("UNIX_OSPFServiceConfiguration20.mof")
#pragma include ("UNIX_DeviceSAPImplementation20.mof")
#pragma include ("UNIX_PortImplementsEndpoint20.mof")
#pragma include ("UNIX_USBConnection20.mof")
#pragma include ("UNIX_SerialInterface20.mof")
#pragma include ("UNIX_USBControllerHasHub20.mof")
#pragma include ("UNIX_SCSIInterface20.mof")
#pragma include ("UNIX_Mount20.mof")
#pragma include ("UNIX_RouteForwardedByService20.mof")
#pragma include ("UNIX_ForwardedRoutes20.mof")
#pragma include ("UNIX_StorageSettingsAssociatedToCapabilities20.mof")
#pragma include ("UNIX_StorageSettingsGeneratedFromCapabilities20.mof")
#pragma include ("UNIX_TransparentBridgingDynamicForwarding20.mof")
#pragma include ("UNIX_MorePersonInfo20.mof")
#pragma include ("UNIX_ReflectorNonClientService20.mof")
#pragma include ("UNIX_SoftwareElementSAPImplementation20.mof")
#pragma include ("UNIX_MediaPresent20.mof")
#pragma include ("UNIX_RealizesPExtent20.mof")
#pragma include ("UNIX_RealizesDiskPartition20.mof")
#pragma include ("UNIX_RealizesAggregatePExtent20.mof")
#pragma include ("UNIX_RealizedOnSide20.mof")
#pragma include ("UNIX_RealizesTapePartition20.mof")
#pragma include ("UNIX_DeviceSoftware20.mof")
#pragma include ("UNIX_SwitchPortStaticForwarding20.mof")
#pragma include ("UNIX_SystemAdministratorGroup20.mof")
#pragma include ("UNIX_LibraryPackage20.mof")
#pragma include ("UNIX_ComputerSystemPackage20.mof")
#pragma include ("UNIX_OrderedDependency20.mof")
#pragma include ("UNIX_UsersAccount20.mof")
#pragma include ("UNIX_ResourceAllocationFromPool20.mof")
#pragma include ("UNIX_SoftwareFeatureServiceImplementation20.mof")
#pragma include ("UNIX_SnapshotOfExtent20.mof")
#pragma include ("UNIX_SoftwareElementServiceImplementation20.mof")
#pragma include ("UNIX_ProcessExecutable20.mof")
#pragma include ("UNIX_AssociatedSupplyVoltageSensor20.mof")
#pragma include ("UNIX_AssociatedSupplyCurrentSensor20.mof")
#pragma include ("UNIX_JobDestinationJobs20.mof")
#pragma include ("UNIX_OwningPrintQueue20.mof")
#pragma include ("UNIX_IsSpare20.mof")
#pragma include ("UNIX_PrinterServicingJob20.mof")
#pragma include ("UNIX_BGPRoutingPolicy20.mof")
#pragma include ("UNIX_DatabaseAdministrator20.mof")
#pragma include ("UNIX_TrustHierarchy20.mof")
#pragma include ("UNIX_RangesOfConfiguration20.mof")
#pragma include ("UNIX_HeadTailDropQueueBinding20.mof")
#pragma include ("UNIX_DoorAccessToPhysicalElement20.mof")
#pragma include ("UNIX_IPsecPolicyForEndpoint20.mof")
#pragma include ("UNIX_LogInDataFile20.mof")
#pragma include ("UNIX_ParticipatingCS20.mof")
#pragma include ("UNIX_AssociatedDatabaseSystem20.mof")
#pragma include ("UNIX_SnapshotOfVirtualSystem20.mof")
#pragma include ("UNIX_MetricForME20.mof")
#pragma include ("UNIX_IdentificationOfManagedSystem20.mof")
#pragma include ("UNIX_IngressConditioningServiceOnEndpoint20.mof")
#pragma include ("UNIX_SwitchPortSourceRouting20.mof")
#pragma include ("UNIX_VLANFor20.mof")
#pragma include ("UNIX_SwitchPortSpanningTree20.mof")
#pragma include ("UNIX_CalculatesAmong20.mof")
#pragma include ("UNIX_RelatedTransparentBridgingService20.mof")
#pragma include ("UNIX_EgressConditioningServiceOnEndpoint20.mof")
#pragma include ("UNIX_ForwardsAmong20.mof")
#pragma include ("UNIX_SwitchesAmong20.mof")
#pragma include ("UNIX_BGPAttributesForRoute20.mof")
#pragma include ("UNIX_EndpointOfNetworkPipe20.mof")
#pragma include ("UNIX_IKESecretIsNamed20.mof")
#pragma include ("UNIX_KDCIssuesKerberosTicket20.mof")
#pragma include ("UNIX_SharedSecretIsShared20.mof")
#pragma include ("UNIX_LocallyManagedPublicKey20.mof")
#pragma include ("UNIX_CASignsPublicKeyCertificate20.mof")
#pragma include ("UNIX_RouteUsesEndpoint20.mof")
#pragma include ("UNIX_MetricDefForME20.mof")
#pragma include ("UNIX_AllocatedResource20.mof")
#pragma include ("UNIX_AllocatedDMA20.mof")
#pragma include ("UNIX_AuthenticationTarget20.mof")
#pragma include ("UNIX_FilterListsInBGPRouteMap20.mof")
#pragma include ("UNIX_MoreRoleInfo20.mof")
#pragma include ("UNIX_ElementsLinked20.mof")
#pragma include ("UNIX_DiagnosticTestSoftware20.mof")
#pragma include ("UNIX_FilterOfPacketCondition20.mof")
#pragma include ("UNIX_RuleThatGeneratedSA20.mof")
#pragma include ("UNIX_AdapterActiveConnection20.mof")
#pragma include ("UNIX_MetricInstance20.mof")
#pragma include ("UNIX_AssociatedIndicatorLED20.mof")
#pragma include ("UNIX_AuthorizedUse20.mof")
#pragma include ("UNIX_HomeForMedia20.mof")
#pragma include ("UNIX_ReflectorService20.mof")
#pragma include ("UNIX_Phase1SAUsedForPhase220.mof")
#pragma include ("UNIX_LogicalDiskBasedOnVolume20.mof")
#pragma include ("UNIX_LogicalDiskBasedOnVolumeSet20.mof")
#pragma include ("UNIX_LogicalDiskBasedOnPartition20.mof")
#pragma include ("UNIX_ProtectedExtentBasedOn20.mof")
#pragma include ("UNIX_CompositeExtentBasedOn20.mof")
#pragma include ("UNIX_VolumeSetBasedOnPSExtent20.mof")
#pragma include ("UNIX_AggregatePSExtentBasedOnPExtent20.mof")
#pragma include ("UNIX_AggregatePSExtentBasedOnAggregatePExtent20.mof")
#pragma include ("UNIX_DiskPartitionBasedOnVolume20.mof")
#pragma include ("UNIX_TapePartitionOnSurface20.mof")
#pragma include ("UNIX_PSExtentBasedOnPExtent20.mof")
#pragma include ("UNIX_PackageAlarm20.mof")
#pragma include ("UNIX_PackageTempSensor20.mof")
#pragma include ("UNIX_PackageCooling20.mof")
#pragma include ("UNIX_DeviceAccessedByFile20.mof")
#pragma include ("UNIX_SwitchPortDynamicForwarding20.mof")
#pragma include ("UNIX_ConditioningServiceOnEndpoint20.mof")
#pragma include ("UNIX_DoorAccessToDevice20.mof")
#pragma include ("UNIX_LogInDeviceFile20.mof")
#pragma include ("UNIX_RecordAppliesToElement20.mof")
#pragma include ("UNIX_QueueForwardsToPrintSAP20.mof")
#pragma include ("UNIX_LibraryExchange20.mof")
#pragma include ("UNIX_IPsecPolicyForSystem20.mof")
#pragma include ("UNIX_CommMechanismForAdapter20.mof")
#pragma include ("UNIX_ConcreteDependency20.mof")
#pragma include ("UNIX_CalculatedRoutes20.mof")
#pragma include ("UNIX_PortActiveConnection20.mof")
#pragma include ("UNIX_AssociatedAlarm20.mof")
#pragma include ("UNIX_TransformOfPreconfiguredAction20.mof")
#pragma include ("UNIX_UsersCredential20.mof")
#pragma include ("UNIX_PublicPrivateKeyPair20.mof")
#pragma include ("UNIX_NotaryVerifiesBiometric20.mof")
#pragma include ("UNIX_AreaOfConfiguration20.mof")
#pragma include ("UNIX_BGPAdminDistance20.mof")
#pragma include ("UNIX_PeerGatewayForTunnel20.mof")
#pragma include ("UNIX_ElementAllocatedFromPool20.mof")
#pragma include ("UNIX_AuthenticateForUse20.mof")
#pragma include ("UNIX_DeviceServicesLocation20.mof")
#pragma include ("UNIX_PeerOfSAEndpoint20.mof")
#pragma include ("UNIX_ProtocolControllerForUnit20.mof")
#pragma include ("UNIX_ProtocolControllerForPort20.mof")
#pragma include ("UNIX_ProtocolControllerAccessesUnit20.mof")
#pragma include ("UNIX_AssociatedProtocolController20.mof")
#pragma include ("UNIX_CAHasPublicCertificate20.mof")
#pragma include ("UNIX_InboundVLAN20.mof")
#pragma include ("UNIX_ActiveConnection20.mof")
#pragma include ("UNIX_Switchable20.mof")
#pragma include ("UNIX_OutboundVLAN20.mof")
#pragma include ("UNIX_EndpointForIPNetworkConnection20.mof")
#pragma include ("UNIX_SwitchPortPair20.mof")
#pragma include ("UNIX_BGPPeerGroupService20.mof")
#pragma include ("UNIX_AuthorizationTarget20.mof")
#pragma include ("UNIX_ReflectorClientService20.mof")
#pragma include ("UNIX_SystemAdministrator20.mof")
#pragma include ("UNIX_MoreOrganizationInfo20.mof")
#pragma include ("UNIX_PrinterServicingQueue20.mof")
#pragma include ("UNIX_ProvidesEndpoint20.mof")
#pragma include ("UNIX_CommMechanismForManager20.mof")
#pragma include ("UNIX_ClusterServiceAccessBySAP20.mof")
#pragma include ("UNIX_BootServiceAccessBySAP20.mof")
#pragma include ("UNIX_AssociatedNextHop20.mof")
#pragma include ("UNIX_SuppliesPower20.mof")
#pragma include ("UNIX_ConnectedTo20.mof")
#pragma include ("UNIX_SlotInSlot20.mof")
#pragma include ("UNIX_AccountMapsToAccount20.mof")
#pragma include ("UNIX_AssociatedCooling20.mof")
#pragma include ("UNIX_CollectionInSystem20.mof")
#pragma include ("UNIX_ReplaceableProductFRU20.mof")
#pragma include ("UNIX_ElementCapabilities20.mof")
#pragma include ("UNIX_ElementProfile20.mof")
#pragma include ("UNIX_AuthorizedTarget20.mof")
#pragma include ("UNIX_Error20.mof")
#pragma include ("UNIX_ProductFRU20.mof")
#pragma include ("UNIX_FromDirectorySpecification20.mof")
#pragma include ("UNIX_RecordInLog20.mof")
#pragma include ("UNIX_CollectionSetting20.mof")
#pragma include ("UNIX_CollectionConfiguration20.mof")
#pragma include ("UNIX_SystemInNamespace20.mof")
#pragma include ("UNIX_ElementCapacity20.mof")
#pragma include ("UNIX_ProductSoftwareFeatures20.mof")
#pragma include ("UNIX_ProductParentChild20.mof")
#pragma include ("UNIX_StorageDefect20.mof")
#pragma include ("UNIX_CollectionInOrganization20.mof")
#pragma include ("UNIX_ServiceAffectsElement20.mof")
#pragma include ("UNIX_FRUIncludesProduct20.mof")
#pragma include ("UNIX_OwningCollectionElement20.mof")
#pragma include ("UNIX_SystemSettingContext20.mof")
#pragma include ("UNIX_ElementLocation20.mof")
#pragma include ("UNIX_ServiceAvailableToElement20.mof")
#pragma include ("UNIX_ActionSequence20.mof")
#pragma include ("UNIX_DiagnosticResultForTest20.mof")
#pragma include ("UNIX_DiagnosticResultForMSE20.mof")
#pragma include ("UNIX_CompatibleProduct20.mof")
#pragma include ("UNIX_SCSIInitiatorTargetLogicalUnitPath20.mof")
#pragma include ("UNIX_FRUIncludesSoftwareFeature20.mof")
#pragma include ("UNIX_InstalledSoftwareIdentity20.mof")
#pragma include ("UNIX_InstalledSoftwareElement20.mof")
#pragma include ("UNIX_FibrePortActiveLogin20.mof")
#pragma include ("UNIX_CollectedCollections20.mof")
#pragma include ("UNIX_ElementConfiguration20.mof")
#pragma include ("UNIX_CorrespondingSettingDataRecord20.mof")
#pragma include ("UNIX_AffectedJobElement20.mof")
#pragma include ("UNIX_NetworksInAdminDomain20.mof")
#pragma include ("UNIX_OwningJobElement20.mof")
#pragma include ("UNIX_ToDirectoryAction20.mof")
#pragma include ("UNIX_SAPAvailableForElement20.mof")
#pragma include ("UNIX_DiagnosticResultInPackage20.mof")
#pragma include ("UNIX_RelatedStatistics20.mof")
#pragma include ("UNIX_BGPClustersInAS20.mof")
#pragma include ("UNIX_CredentialContext20.mof")
#pragma include ("UNIX_FromDirectoryAction20.mof")
#pragma include ("UNIX_AFRelatedServices20.mof")
#pragma include ("UNIX_RoleLimitedToTarget20.mof")
#pragma include ("UNIX_ActsAsSpare20.mof")
#pragma include ("UNIX_OrgStructure20.mof")
#pragma include ("UNIX_AssociatedJobMethodResult20.mof")
#pragma include ("UNIX_SettingContext20.mof")
#pragma include ("UNIX_FRUPhysicalElements20.mof")
#pragma include ("UNIX_ElementStatisticalData20.mof")
#pragma include ("UNIX_NextService20.mof")
#pragma include ("UNIX_LogicalNetworkService20.mof")
#pragma include ("UNIX_ElementSetting20.mof")
#pragma include ("UNIX_DependencyContext20.mof")
#pragma include ("UNIX_ProductSupport20.mof")
#pragma include ("UNIX_RelatedStatisticalData20.mof")
#pragma include ("UNIX_ElementSecuritySensitivity20.mof")
#pragma include ("UNIX_AssignedIdentity20.mof")
#pragma include ("UNIX_Synchronized20.mof")
#pragma include ("UNIX_CorrespondingSettingsRecord20.mof")
#pragma include ("UNIX_LogManagesRecord20.mof")
#pragma include ("UNIX_ServiceProcess20.mof")
#pragma include ("UNIX_NextServiceAfterMeter20.mof")
#pragma include ("UNIX_QueueToSchedule20.mof")
#pragma include ("UNIX_ApplicationSystemDirectory20.mof")
#pragma include ("UNIX_PolicySetAppliesToElement20.mof")
#pragma include ("UNIX_ParameterValueSources20.mof")
#pragma include ("UNIX_DirectorySpecificationFile20.mof")
#pragma include ("UNIX_AssociatedPrivilege20.mof")
#pragma include ("UNIX_ParametersForMethod20.mof")
#pragma include ("UNIX_Export20.mof")
#pragma include ("UNIX_ElementConformsToProfile20.mof")
#pragma include ("UNIX_AdjacentSlots20.mof")
#pragma include ("UNIX_ProductPhysicalElements20.mof")
#pragma include ("UNIX_IdentityContext20.mof")
#pragma include ("UNIX_ToDirectorySpecification20.mof")
#pragma include ("UNIX_InstalledProductImage20.mof")
#pragma include ("UNIX_ProductProductDependency20.mof")
#pragma include ("UNIX_DiagnosticResult20.mof")
#pragma include ("UNIX_SchedulingServiceToSchedule20.mof")
#pragma include ("UNIX_AbstractIndicationSubscription20.mof")
#pragma include ("UNIX_AuthorizedSubject20.mof")
#pragma include ("UNIX_SettingsDefineState20.mof")
#pragma include ("UNIX_SoftwareElementActions20.mof")
#pragma include ("UNIX_SoftwareElementChecks20.mof")
#pragma include ("UNIX_AssociatedBlockStatisticsManifestCollection20.mof")
#pragma include ("UNIX_ParticipatesInSet20.mof")
#pragma include ("UNIX_ConfigurationComponent20.mof")
#pragma include ("UNIX_CurrentTime20.mof")