//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Abstract, Aggregation, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_Component is a generic association used to establish \'part "
       "of\' relationships between Managed Elements. For example, it "
       "could be used to define the components or parts of a System." )]
class CIM_Component {

      [Key, Aggregate, Description ( 
          "The parent element in the association." )]
   CIM_ManagedElement REF GroupComponent;

      [Key, Description ( "The child element in the association." )]
   CIM_ManagedElement REF PartComponent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_MemberOfCollection" }, 
    Aggregation, Version ( "2.13.0" ), 
    UMLPackagePath ( "CIM::Core::Redundancy" ), 
    Description ( 
       "A RedundancyGroup aggregates Managed System Elements and "
       "indicates that these elements, taken together, provide "
       "redundancy. All elements aggregated in a RedundancyGroup "
       "should be instantiations of the same object class. \n"
       "The use of this class is being depreacted in lieu of using "
       "MemberOfCollection in conjunction with RedundancySet." )]
class CIM_RedundancyComponent : CIM_Component {

      [Deprecated { "CIM_MemberOfCollection.Collection" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Description ( 
          "The RedundancyComponent association indicates that \'this "
          "set of fans\' or \'these physical extents\' participate "
          "in a single RedundancyGroup." )]
   CIM_RedundancyGroup REF GroupComponent;

      [Deprecated { "CIM_MemberOfCollection.Member" }, 
       Override ( "PartComponent" ), 
       Description ( "The component of the redundancy group." )]
   CIM_ManagedSystemElement REF PartComponent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_MemberOfCollection" }, 
    Aggregation, Version ( "2.13.0" ), 
    UMLPackagePath ( "CIM::Core::Redundancy" ), 
    Description ( 
       "Describes the StorageExtents participating in a Storage "
       "RedundancyGroup. \n"
       "The use of this class is being deprecated in lieu of using "
       "MemberOfCollection in conjunction with StorageRedundancySet." )]
class CIM_ExtentRedundancyComponent : CIM_RedundancyComponent {

      [Deprecated { "CIM_MemberOfCollection.Collection" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Description ( "The StorageRedundancyGroup." )]
   CIM_StorageRedundancyGroup REF GroupComponent;

      [Deprecated { "CIM_MemberOfCollection.Member" }, 
       Override ( "PartComponent" ), 
       Description ( 
          "The StorageExtent participating in the RedundancyGroup." )]
   CIM_StorageExtent REF PartComponent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Deprecated { "CIM_ExtentRedundancyComponent" }, 
    Aggregation, Version ( "2.7.0" ), 
    UMLPackagePath ( "CIM::Device::SccExtents" ), 
    Description ( 
       "Describes the AggregatePExtent in a StorageRedundancyGroup. "
       "However, there is no need for the specificity of this "
       "association. It is deprecated in lieu of the generic "
       "ExtentRedundancyComponent relationship, its superclass." )]
class CIM_AggregateRedundancyComponent : CIM_ExtentRedundancyComponent {

      [Deprecated { "CIM_ExtentRedundancyComponent.GroupComponent" }, 
       Aggregate, Override ( "GroupComponent" ), 
       Description ( "The StorageRedundancyGroup." )]
   CIM_StorageRedundancyGroup REF GroupComponent;

      [Deprecated { "CIM_ExtentRedundancyComponent.PartComponent" }, 
       Override ( "PartComponent" ), 
       Description ( 
          "The AggregatePExtent participating in the RedundancyGroup."
           )]
   CIM_AggregatePExtent REF PartComponent;


};



class UNIX_AggregateRedundancyComponent : CIM_AggregateRedundancyComponent
{

};

