//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Abstract, Version ( "2.10.0" ), 
    UMLPackagePath ( "CIM::Core::CoreElements" ), 
    Description ( 
       "CIM_Dependency is a generic association used to establish "
       "dependency relationships between ManagedElements." )]
class CIM_Dependency {

      [Key, Description ( 
          "Antecedent represents the independent object in this association."
           )]
   CIM_ManagedElement REF Antecedent;

      [Key, Description ( 
          "Dependent represents the object that is dependent on the "
          "Antecedent." )]
   CIM_ManagedElement REF Dependent;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::System::FilesystemServices" ), 
    Description ( 
       "This association defines settings that can be used to create "
       "or modify elements. Unlike ElementSettingData, these settings "
       "are not used to express the characteristics of existing "
       "managed elements. \n"
       "Typically, the capabilities associated with this class define "
       "the characteristics of a service in creating or modifying "
       "elements that are dependent on the service directly or "
       "indirectly. A CIM Client may use this association to find "
       "SettingData instances that can be used to create or modify "
       "these dependent elements." )]
class CIM_SettingAssociatedToCapabilities : CIM_Dependency {

      [Override ( "Antecedent" ), 
       Description ( "The Capabilities." )]
   CIM_Capabilities REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The Setting." )]
   CIM_SettingData REF Dependent;

      [Required, Description ( 
          "If an element whose characteristics are described by the "
          "associated Capabilities instance has a dependent element "
          "created or modified without specifying an associated "
          "SettingData instance, then the default SettingData will "
          "be used in that operation." )]
   boolean DefaultSetting = false;


};


// Copyright (c) 2005 DMTF.  All rights reserved.
   [Association, Version ( "2.11.0" ), 
    UMLPackagePath ( "CIM::Device::StorageServices" ), 
    Description ( 
       "This association define StorageSettings that reflect the "
       "capabilities of the associated StorageCapabilities. The "
       "associated StorageSetting may not define the operational "
       "characteristics (through settings properties) of any storage "
       "element. Certain StorageSetting instances can be defined as "
       "\"Fixed = Not Changeable\" by using the \"ChangeableType\" "
       "attribute. \"Fixed\" settings have this special association. "
       "This association should be defined between \"Fixed - Not "
       "Changeable\" instances of StorageSetting with the "
       "StorageCapabilities instances that are associated with the "
       "StoragePools which support the storage characteristics "
       "described by the StorageSetting instance. \n"
       "Fixed settings may be associated to many StorageCapabilities." )]
class CIM_StorageSettingsAssociatedToCapabilities : CIM_SettingAssociatedToCapabilities {

      [Override ( "Antecedent" ), 
       Description ( "The StorageCapabilities." )]
   CIM_StorageCapabilities REF Antecedent;

      [Override ( "Dependent" ), 
       Description ( "The fixed and predefined StorageSetting." )]
   CIM_StorageSetting REF Dependent;


};



class UNIX_StorageSettingsAssociatedToCapabilities : CIM_StorageSettingsAssociatedToCapabilities
{

};

